[options]
girs_dir = "gir-files/"
library = "Atspi"
version = "2.0"
min_cfg_version = "2.28"
target_path = "."
work_mode = "normal"
generate_safety_asserts = true
deprecate_by_min_version = true
single_version_file = true



generate = [
            # "Atspi.Accessible",
            # see [[object]] definition
            "Atspi.Action",
            # "Atspi.Application",
            # 'Missing memory management functions for Atspi.Application'
            "Atspi.Cache",
            "Atspi.Collection",
            "Atspi.CollectionMatchType",
            "Atspi.CollectionSortOrder",
            "Atspi.CollectionTreeTraversalType",
            "Atspi.Component",
            "Atspi.ComponentLayer",
            "Atspi.ControllerEventMask",
            "Atspi.CoordType",
            "Atspi.DeviceEvent",
            "Atspi.DeviceEventMask",
            # "Atspi.DeviceListener",
            # function `atspi_device_listener_new`'s callback `callback` has invalid user data#

            "Atspi.DeviceListenerCB",
            "Atspi.DeviceListenerMode",

            # Configured object `Atspi.DeviceListenerMode` missing from the library
            "Atspi.DeviceListenerSimpleCB",
            # "Atspi.Document",
            # see [[object]] definition

            "Atspi.Event",
            # "Atspi.EventListener",
            # function `atspi_event_listener_new_simple`'s callback `callback` without associated user data
            # "Atspi.EventListenerMode",
            # 'Missing memory management functions for Atspi.EventListenerMode'
            "Atspi.EventListenerCB",
            "Atspi.EventLinstenerSimpleCB",
            "Atspi.EditableText",
            "Atspi.Hyperlink",
            "Atspi.Hypertext",
            "Atspi.Image",
            "Atspi.KeyDefinition",
            "Atspi.KeyEventMask",
            "Atspi.KeyListenerSyncType",
            "Atspi.KeyMaskType",
            # "Atspi.KeySet",
            # 'Missing memory management functions for Atspi.KeySet'
            "Atspi.KeystrokeListener",
            "Atspi.KeySynthType",
            "Atspi.MatchRule",
            "Atspi.Object",
            "Atspi.Point",
            "Atspi.Range",
            # "Atspi.Rect",
            # Manual methods
            "Atspi.Relation",
            "Atspi.RelationType",
            "Atspi.Role",
            "Atspi.Selection",
            "Atspi.StateSet",
            "Atspi.StateType",
            "Atspi.Table",
            "Atspi.TableCell",
            # "Atspi.Text",
            # see [[object]] definition

            "Atspi.TextBoundaryType",
            "Atspi.TextClipType",
            "Atspi.TextGranularity",
            "Atspi.TextRange",
            "Atspi.Value",
        ]

manual = [
         "GLib.Error",
         "GLib.DestroyNotify",
         "GLib.MainContext",
         "DBus.Connection",
         "Atspi.Rect",
         "Atspi.DeviceListener"
       ]

[[object]]
name = "Atspi.Text"
status = "generate"
    [[object.function]]
    name = "get_attribute_run"
    # *.HashTable TypeId { ns_id: 0, id: 28 }/TypeId { ns_id: 0, id: 28 }
    ignore = true
    [[object.function]]
    name = "get_default_attributes"
    # *.HashTable TypeId { ns_id: 0, id: 28 }/TypeId { ns_id: 0, id: 28 }
    ignore = true
    [[object.function]]
    name = "get_text_attributes"
    # *.HashTable TypeId { ns_id: 0, id: 28 }/TypeId { ns_id: 0, id: 28 }
    ignore = true

[[object]]
name = "Atspi.Accessible"
status = "generate"
    [[object.function]]
    name = "get_attributes"
    # *.HashTable TypeId { ns_id: 0, id: 28 }/TypeId { ns_id: 0, id: 28 }
    ignore = true

[[object]]
name = "Atspi.Document"
status = "generate"
    [[object.function]]
    name = "get_document_attributes"
    # *.HashTable TypeId { ns_id: 0, id: 28 }/TypeId { ns_id: 0, id: 28 }
    ignore = true

[[object]]
name = "Atspi.Application"
status = "generate"

[[object]]
name = "Atspi.Application"
status = "generate"
