// This file was generated by gir (https://github.com/gtk-rs/gir @ 7cca816)
// from gir-files (https://github.com/gtk-rs/gir-files @ 02dfee2)
// DO NOT EDIT

#[allow(unused_imports)]
use auto::*;

pub type ControllerEventMask = u32;
pub type DeviceEventMask = u32;
pub type KeyEventMask = u32;
pub type KeyMaskType = u32;
pub type KeystrokeListener = /*Unimplemented*/();
