// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use glib::translate::*;
use std::fmt;

glib::glib_wrapper! {
    pub struct Application(Object<ffi::AtspiApplication, ffi::AtspiApplicationClass>);

    match fn {
        get_type => || ffi::atspi_application_get_type(),
    }
}

impl Application {}

pub const NONE_APPLICATION: Option<&Application> = None;

impl fmt::Display for Application {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("Application")
    }
}
