// This file was generated by gir (https://github.com/gtk-rs/gir @ 7cca816)
// from gir-files (https://github.com/gtk-rs/gir-files @ 02dfee2)
// DO NOT EDIT

use atspi_sys;
use gobject_sys;

glib_wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct DeviceEvent(Boxed<atspi_sys::AtspiDeviceEvent>);

    match fn {
        copy => |ptr| gobject_sys::g_boxed_copy(atspi_sys::atspi_device_event_get_type(), ptr as *mut _) as *mut atspi_sys::AtspiDeviceEvent,
        free => |ptr| gobject_sys::g_boxed_free(atspi_sys::atspi_device_event_get_type(), ptr as *mut _),
        get_type => || atspi_sys::atspi_device_event_get_type(),
    }
}
