// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use atspi_sys;
use glib::translate::*;
use glib::value::FromValue;
use glib::value::FromValueOptional;
use glib::value::SetValue;
use glib::value::Value;
use glib::StaticType;
use glib::Type;
use gobject_sys;
use std::fmt;

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[derive(Clone, Copy)]
#[non_exhaustive]
pub enum CollectionMatchType {
    Invalid,
    All,
    Any,
    None,
    Empty,
    LastDefined,
    #[doc(hidden)]
    __Unknown(i32),
}

impl fmt::Display for CollectionMatchType {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "CollectionMatchType::{}", match *self {
            CollectionMatchType::Invalid => "Invalid",
            CollectionMatchType::All => "All",
            CollectionMatchType::Any => "Any",
            CollectionMatchType::None => "None",
            CollectionMatchType::Empty => "Empty",
            CollectionMatchType::LastDefined => "LastDefined",
            _ => "Unknown",
        })
    }
}

#[doc(hidden)]
impl ToGlib for CollectionMatchType {
    type GlibType = atspi_sys::AtspiCollectionMatchType;

    fn to_glib(&self) -> atspi_sys::AtspiCollectionMatchType {
        match *self {
            CollectionMatchType::Invalid => atspi_sys::ATSPI_Collection_MATCH_INVALID,
            CollectionMatchType::All => atspi_sys::ATSPI_Collection_MATCH_ALL,
            CollectionMatchType::Any => atspi_sys::ATSPI_Collection_MATCH_ANY,
            CollectionMatchType::None => atspi_sys::ATSPI_Collection_MATCH_NONE,
            CollectionMatchType::Empty => atspi_sys::ATSPI_Collection_MATCH_EMPTY,
            CollectionMatchType::LastDefined => atspi_sys::ATSPI_Collection_MATCH_LAST_DEFINED,
            CollectionMatchType::__Unknown(value) => value
        }
    }
}

#[doc(hidden)]
impl FromGlib<atspi_sys::AtspiCollectionMatchType> for CollectionMatchType {
    fn from_glib(value: atspi_sys::AtspiCollectionMatchType) -> Self {
        skip_assert_initialized!();
        match value {
            0 => CollectionMatchType::Invalid,
            1 => CollectionMatchType::All,
            2 => CollectionMatchType::Any,
            3 => CollectionMatchType::None,
            4 => CollectionMatchType::Empty,
            5 => CollectionMatchType::LastDefined,
            value => CollectionMatchType::__Unknown(value),
        }
    }
}

impl StaticType for CollectionMatchType {
    fn static_type() -> Type {
        unsafe { from_glib(atspi_sys::atspi_collection_match_type_get_type()) }
    }
}

impl<'a> FromValueOptional<'a> for CollectionMatchType {
    unsafe fn from_value_optional(value: &Value) -> Option<Self> {
        Some(FromValue::from_value(value))
    }
}

impl<'a> FromValue<'a> for CollectionMatchType {
    unsafe fn from_value(value: &Value) -> Self {
        from_glib(gobject_sys::g_value_get_enum(value.to_glib_none().0))
    }
}

impl SetValue for CollectionMatchType {
    unsafe fn set_value(value: &mut Value, this: &Self) {
        gobject_sys::g_value_set_enum(value.to_glib_none_mut().0, this.to_glib())
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[derive(Clone, Copy)]
#[non_exhaustive]
pub enum CollectionSortOrder {
    Invalid,
    Canonical,
    Flow,
    Tab,
    ReverseCanonical,
    ReverseFlow,
    ReverseTab,
    LastDefined,
    #[doc(hidden)]
    __Unknown(i32),
}

impl fmt::Display for CollectionSortOrder {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "CollectionSortOrder::{}", match *self {
            CollectionSortOrder::Invalid => "Invalid",
            CollectionSortOrder::Canonical => "Canonical",
            CollectionSortOrder::Flow => "Flow",
            CollectionSortOrder::Tab => "Tab",
            CollectionSortOrder::ReverseCanonical => "ReverseCanonical",
            CollectionSortOrder::ReverseFlow => "ReverseFlow",
            CollectionSortOrder::ReverseTab => "ReverseTab",
            CollectionSortOrder::LastDefined => "LastDefined",
            _ => "Unknown",
        })
    }
}

#[doc(hidden)]
impl ToGlib for CollectionSortOrder {
    type GlibType = atspi_sys::AtspiCollectionSortOrder;

    fn to_glib(&self) -> atspi_sys::AtspiCollectionSortOrder {
        match *self {
            CollectionSortOrder::Invalid => atspi_sys::ATSPI_Collection_SORT_ORDER_INVALID,
            CollectionSortOrder::Canonical => atspi_sys::ATSPI_Collection_SORT_ORDER_CANONICAL,
            CollectionSortOrder::Flow => atspi_sys::ATSPI_Collection_SORT_ORDER_FLOW,
            CollectionSortOrder::Tab => atspi_sys::ATSPI_Collection_SORT_ORDER_TAB,
            CollectionSortOrder::ReverseCanonical => atspi_sys::ATSPI_Collection_SORT_ORDER_REVERSE_CANONICAL,
            CollectionSortOrder::ReverseFlow => atspi_sys::ATSPI_Collection_SORT_ORDER_REVERSE_FLOW,
            CollectionSortOrder::ReverseTab => atspi_sys::ATSPI_Collection_SORT_ORDER_REVERSE_TAB,
            CollectionSortOrder::LastDefined => atspi_sys::ATSPI_Collection_SORT_ORDER_LAST_DEFINED,
            CollectionSortOrder::__Unknown(value) => value
        }
    }
}

#[doc(hidden)]
impl FromGlib<atspi_sys::AtspiCollectionSortOrder> for CollectionSortOrder {
    fn from_glib(value: atspi_sys::AtspiCollectionSortOrder) -> Self {
        skip_assert_initialized!();
        match value {
            0 => CollectionSortOrder::Invalid,
            1 => CollectionSortOrder::Canonical,
            2 => CollectionSortOrder::Flow,
            3 => CollectionSortOrder::Tab,
            4 => CollectionSortOrder::ReverseCanonical,
            5 => CollectionSortOrder::ReverseFlow,
            6 => CollectionSortOrder::ReverseTab,
            7 => CollectionSortOrder::LastDefined,
            value => CollectionSortOrder::__Unknown(value),
        }
    }
}

impl StaticType for CollectionSortOrder {
    fn static_type() -> Type {
        unsafe { from_glib(atspi_sys::atspi_collection_sort_order_get_type()) }
    }
}

impl<'a> FromValueOptional<'a> for CollectionSortOrder {
    unsafe fn from_value_optional(value: &Value) -> Option<Self> {
        Some(FromValue::from_value(value))
    }
}

impl<'a> FromValue<'a> for CollectionSortOrder {
    unsafe fn from_value(value: &Value) -> Self {
        from_glib(gobject_sys::g_value_get_enum(value.to_glib_none().0))
    }
}

impl SetValue for CollectionSortOrder {
    unsafe fn set_value(value: &mut Value, this: &Self) {
        gobject_sys::g_value_set_enum(value.to_glib_none_mut().0, this.to_glib())
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[derive(Clone, Copy)]
#[non_exhaustive]
pub enum CollectionTreeTraversalType {
    RestrictChildren,
    RestrictSibling,
    Inorder,
    LastDefined,
    #[doc(hidden)]
    __Unknown(i32),
}

impl fmt::Display for CollectionTreeTraversalType {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "CollectionTreeTraversalType::{}", match *self {
            CollectionTreeTraversalType::RestrictChildren => "RestrictChildren",
            CollectionTreeTraversalType::RestrictSibling => "RestrictSibling",
            CollectionTreeTraversalType::Inorder => "Inorder",
            CollectionTreeTraversalType::LastDefined => "LastDefined",
            _ => "Unknown",
        })
    }
}

#[doc(hidden)]
impl ToGlib for CollectionTreeTraversalType {
    type GlibType = atspi_sys::AtspiCollectionTreeTraversalType;

    fn to_glib(&self) -> atspi_sys::AtspiCollectionTreeTraversalType {
        match *self {
            CollectionTreeTraversalType::RestrictChildren => atspi_sys::ATSPI_Collection_TREE_RESTRICT_CHILDREN,
            CollectionTreeTraversalType::RestrictSibling => atspi_sys::ATSPI_Collection_TREE_RESTRICT_SIBLING,
            CollectionTreeTraversalType::Inorder => atspi_sys::ATSPI_Collection_TREE_INORDER,
            CollectionTreeTraversalType::LastDefined => atspi_sys::ATSPI_Collection_TREE_LAST_DEFINED,
            CollectionTreeTraversalType::__Unknown(value) => value
        }
    }
}

#[doc(hidden)]
impl FromGlib<atspi_sys::AtspiCollectionTreeTraversalType> for CollectionTreeTraversalType {
    fn from_glib(value: atspi_sys::AtspiCollectionTreeTraversalType) -> Self {
        skip_assert_initialized!();
        match value {
            0 => CollectionTreeTraversalType::RestrictChildren,
            1 => CollectionTreeTraversalType::RestrictSibling,
            2 => CollectionTreeTraversalType::Inorder,
            3 => CollectionTreeTraversalType::LastDefined,
            value => CollectionTreeTraversalType::__Unknown(value),
        }
    }
}

impl StaticType for CollectionTreeTraversalType {
    fn static_type() -> Type {
        unsafe { from_glib(atspi_sys::atspi_collection_tree_traversal_type_get_type()) }
    }
}

impl<'a> FromValueOptional<'a> for CollectionTreeTraversalType {
    unsafe fn from_value_optional(value: &Value) -> Option<Self> {
        Some(FromValue::from_value(value))
    }
}

impl<'a> FromValue<'a> for CollectionTreeTraversalType {
    unsafe fn from_value(value: &Value) -> Self {
        from_glib(gobject_sys::g_value_get_enum(value.to_glib_none().0))
    }
}

impl SetValue for CollectionTreeTraversalType {
    unsafe fn set_value(value: &mut Value, this: &Self) {
        gobject_sys::g_value_set_enum(value.to_glib_none_mut().0, this.to_glib())
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[derive(Clone, Copy)]
#[non_exhaustive]
pub enum ComponentLayer {
    Invalid,
    Background,
    Canvas,
    Widget,
    Mdi,
    Popup,
    Overlay,
    Window,
    LastDefined,
    #[doc(hidden)]
    __Unknown(i32),
}

impl fmt::Display for ComponentLayer {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "ComponentLayer::{}", match *self {
            ComponentLayer::Invalid => "Invalid",
            ComponentLayer::Background => "Background",
            ComponentLayer::Canvas => "Canvas",
            ComponentLayer::Widget => "Widget",
            ComponentLayer::Mdi => "Mdi",
            ComponentLayer::Popup => "Popup",
            ComponentLayer::Overlay => "Overlay",
            ComponentLayer::Window => "Window",
            ComponentLayer::LastDefined => "LastDefined",
            _ => "Unknown",
        })
    }
}

#[doc(hidden)]
impl ToGlib for ComponentLayer {
    type GlibType = atspi_sys::AtspiComponentLayer;

    fn to_glib(&self) -> atspi_sys::AtspiComponentLayer {
        match *self {
            ComponentLayer::Invalid => atspi_sys::ATSPI_LAYER_INVALID,
            ComponentLayer::Background => atspi_sys::ATSPI_LAYER_BACKGROUND,
            ComponentLayer::Canvas => atspi_sys::ATSPI_LAYER_CANVAS,
            ComponentLayer::Widget => atspi_sys::ATSPI_LAYER_WIDGET,
            ComponentLayer::Mdi => atspi_sys::ATSPI_LAYER_MDI,
            ComponentLayer::Popup => atspi_sys::ATSPI_LAYER_POPUP,
            ComponentLayer::Overlay => atspi_sys::ATSPI_LAYER_OVERLAY,
            ComponentLayer::Window => atspi_sys::ATSPI_LAYER_WINDOW,
            ComponentLayer::LastDefined => atspi_sys::ATSPI_LAYER_LAST_DEFINED,
            ComponentLayer::__Unknown(value) => value
        }
    }
}

#[doc(hidden)]
impl FromGlib<atspi_sys::AtspiComponentLayer> for ComponentLayer {
    fn from_glib(value: atspi_sys::AtspiComponentLayer) -> Self {
        skip_assert_initialized!();
        match value {
            0 => ComponentLayer::Invalid,
            1 => ComponentLayer::Background,
            2 => ComponentLayer::Canvas,
            3 => ComponentLayer::Widget,
            4 => ComponentLayer::Mdi,
            5 => ComponentLayer::Popup,
            6 => ComponentLayer::Overlay,
            7 => ComponentLayer::Window,
            8 => ComponentLayer::LastDefined,
            value => ComponentLayer::__Unknown(value),
        }
    }
}

impl StaticType for ComponentLayer {
    fn static_type() -> Type {
        unsafe { from_glib(atspi_sys::atspi_component_layer_get_type()) }
    }
}

impl<'a> FromValueOptional<'a> for ComponentLayer {
    unsafe fn from_value_optional(value: &Value) -> Option<Self> {
        Some(FromValue::from_value(value))
    }
}

impl<'a> FromValue<'a> for ComponentLayer {
    unsafe fn from_value(value: &Value) -> Self {
        from_glib(gobject_sys::g_value_get_enum(value.to_glib_none().0))
    }
}

impl SetValue for ComponentLayer {
    unsafe fn set_value(value: &mut Value, this: &Self) {
        gobject_sys::g_value_set_enum(value.to_glib_none_mut().0, this.to_glib())
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[derive(Clone, Copy)]
#[non_exhaustive]
pub enum CoordType {
    Screen,
    Window,
    Parent,
    #[doc(hidden)]
    __Unknown(i32),
}

impl fmt::Display for CoordType {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "CoordType::{}", match *self {
            CoordType::Screen => "Screen",
            CoordType::Window => "Window",
            CoordType::Parent => "Parent",
            _ => "Unknown",
        })
    }
}

#[doc(hidden)]
impl ToGlib for CoordType {
    type GlibType = atspi_sys::AtspiCoordType;

    fn to_glib(&self) -> atspi_sys::AtspiCoordType {
        match *self {
            CoordType::Screen => atspi_sys::ATSPI_COORD_TYPE_SCREEN,
            CoordType::Window => atspi_sys::ATSPI_COORD_TYPE_WINDOW,
            CoordType::Parent => atspi_sys::ATSPI_COORD_TYPE_PARENT,
            CoordType::__Unknown(value) => value
        }
    }
}

#[doc(hidden)]
impl FromGlib<atspi_sys::AtspiCoordType> for CoordType {
    fn from_glib(value: atspi_sys::AtspiCoordType) -> Self {
        skip_assert_initialized!();
        match value {
            0 => CoordType::Screen,
            1 => CoordType::Window,
            2 => CoordType::Parent,
            value => CoordType::__Unknown(value),
        }
    }
}

impl StaticType for CoordType {
    fn static_type() -> Type {
        unsafe { from_glib(atspi_sys::atspi_coord_type_get_type()) }
    }
}

impl<'a> FromValueOptional<'a> for CoordType {
    unsafe fn from_value_optional(value: &Value) -> Option<Self> {
        Some(FromValue::from_value(value))
    }
}

impl<'a> FromValue<'a> for CoordType {
    unsafe fn from_value(value: &Value) -> Self {
        from_glib(gobject_sys::g_value_get_enum(value.to_glib_none().0))
    }
}

impl SetValue for CoordType {
    unsafe fn set_value(value: &mut Value, this: &Self) {
        gobject_sys::g_value_set_enum(value.to_glib_none_mut().0, this.to_glib())
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[derive(Clone, Copy)]
#[non_exhaustive]
pub enum KeySynthType {
    Press,
    Release,
    Pressrelease,
    Sym,
    String,
    Lockmodifiers,
    Unlockmodifiers,
    #[doc(hidden)]
    __Unknown(i32),
}

impl fmt::Display for KeySynthType {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "KeySynthType::{}", match *self {
            KeySynthType::Press => "Press",
            KeySynthType::Release => "Release",
            KeySynthType::Pressrelease => "Pressrelease",
            KeySynthType::Sym => "Sym",
            KeySynthType::String => "String",
            KeySynthType::Lockmodifiers => "Lockmodifiers",
            KeySynthType::Unlockmodifiers => "Unlockmodifiers",
            _ => "Unknown",
        })
    }
}

#[doc(hidden)]
impl ToGlib for KeySynthType {
    type GlibType = atspi_sys::AtspiKeySynthType;

    fn to_glib(&self) -> atspi_sys::AtspiKeySynthType {
        match *self {
            KeySynthType::Press => atspi_sys::ATSPI_KEY_PRESS,
            KeySynthType::Release => atspi_sys::ATSPI_KEY_RELEASE,
            KeySynthType::Pressrelease => atspi_sys::ATSPI_KEY_PRESSRELEASE,
            KeySynthType::Sym => atspi_sys::ATSPI_KEY_SYM,
            KeySynthType::String => atspi_sys::ATSPI_KEY_STRING,
            KeySynthType::Lockmodifiers => atspi_sys::ATSPI_KEY_LOCKMODIFIERS,
            KeySynthType::Unlockmodifiers => atspi_sys::ATSPI_KEY_UNLOCKMODIFIERS,
            KeySynthType::__Unknown(value) => value
        }
    }
}

#[doc(hidden)]
impl FromGlib<atspi_sys::AtspiKeySynthType> for KeySynthType {
    fn from_glib(value: atspi_sys::AtspiKeySynthType) -> Self {
        skip_assert_initialized!();
        match value {
            0 => KeySynthType::Press,
            1 => KeySynthType::Release,
            2 => KeySynthType::Pressrelease,
            3 => KeySynthType::Sym,
            4 => KeySynthType::String,
            5 => KeySynthType::Lockmodifiers,
            6 => KeySynthType::Unlockmodifiers,
            value => KeySynthType::__Unknown(value),
        }
    }
}

impl StaticType for KeySynthType {
    fn static_type() -> Type {
        unsafe { from_glib(atspi_sys::atspi_key_synth_type_get_type()) }
    }
}

impl<'a> FromValueOptional<'a> for KeySynthType {
    unsafe fn from_value_optional(value: &Value) -> Option<Self> {
        Some(FromValue::from_value(value))
    }
}

impl<'a> FromValue<'a> for KeySynthType {
    unsafe fn from_value(value: &Value) -> Self {
        from_glib(gobject_sys::g_value_get_enum(value.to_glib_none().0))
    }
}

impl SetValue for KeySynthType {
    unsafe fn set_value(value: &mut Value, this: &Self) {
        gobject_sys::g_value_set_enum(value.to_glib_none_mut().0, this.to_glib())
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[derive(Clone, Copy)]
#[non_exhaustive]
pub enum RelationType {
    Null,
    LabelFor,
    LabelledBy,
    ControllerFor,
    ControlledBy,
    MemberOf,
    TooltipFor,
    NodeChildOf,
    NodeParentOf,
    Extended,
    FlowsTo,
    FlowsFrom,
    SubwindowOf,
    Embeds,
    EmbeddedBy,
    PopupFor,
    ParentWindowOf,
    DescriptionFor,
    DescribedBy,
    Details,
    DetailsFor,
    ErrorMessage,
    ErrorFor,
    LastDefined,
    #[doc(hidden)]
    __Unknown(i32),
}

impl fmt::Display for RelationType {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "RelationType::{}", match *self {
            RelationType::Null => "Null",
            RelationType::LabelFor => "LabelFor",
            RelationType::LabelledBy => "LabelledBy",
            RelationType::ControllerFor => "ControllerFor",
            RelationType::ControlledBy => "ControlledBy",
            RelationType::MemberOf => "MemberOf",
            RelationType::TooltipFor => "TooltipFor",
            RelationType::NodeChildOf => "NodeChildOf",
            RelationType::NodeParentOf => "NodeParentOf",
            RelationType::Extended => "Extended",
            RelationType::FlowsTo => "FlowsTo",
            RelationType::FlowsFrom => "FlowsFrom",
            RelationType::SubwindowOf => "SubwindowOf",
            RelationType::Embeds => "Embeds",
            RelationType::EmbeddedBy => "EmbeddedBy",
            RelationType::PopupFor => "PopupFor",
            RelationType::ParentWindowOf => "ParentWindowOf",
            RelationType::DescriptionFor => "DescriptionFor",
            RelationType::DescribedBy => "DescribedBy",
            RelationType::Details => "Details",
            RelationType::DetailsFor => "DetailsFor",
            RelationType::ErrorMessage => "ErrorMessage",
            RelationType::ErrorFor => "ErrorFor",
            RelationType::LastDefined => "LastDefined",
            _ => "Unknown",
        })
    }
}

#[doc(hidden)]
impl ToGlib for RelationType {
    type GlibType = atspi_sys::AtspiRelationType;

    fn to_glib(&self) -> atspi_sys::AtspiRelationType {
        match *self {
            RelationType::Null => atspi_sys::ATSPI_RELATION_NULL,
            RelationType::LabelFor => atspi_sys::ATSPI_RELATION_LABEL_FOR,
            RelationType::LabelledBy => atspi_sys::ATSPI_RELATION_LABELLED_BY,
            RelationType::ControllerFor => atspi_sys::ATSPI_RELATION_CONTROLLER_FOR,
            RelationType::ControlledBy => atspi_sys::ATSPI_RELATION_CONTROLLED_BY,
            RelationType::MemberOf => atspi_sys::ATSPI_RELATION_MEMBER_OF,
            RelationType::TooltipFor => atspi_sys::ATSPI_RELATION_TOOLTIP_FOR,
            RelationType::NodeChildOf => atspi_sys::ATSPI_RELATION_NODE_CHILD_OF,
            RelationType::NodeParentOf => atspi_sys::ATSPI_RELATION_NODE_PARENT_OF,
            RelationType::Extended => atspi_sys::ATSPI_RELATION_EXTENDED,
            RelationType::FlowsTo => atspi_sys::ATSPI_RELATION_FLOWS_TO,
            RelationType::FlowsFrom => atspi_sys::ATSPI_RELATION_FLOWS_FROM,
            RelationType::SubwindowOf => atspi_sys::ATSPI_RELATION_SUBWINDOW_OF,
            RelationType::Embeds => atspi_sys::ATSPI_RELATION_EMBEDS,
            RelationType::EmbeddedBy => atspi_sys::ATSPI_RELATION_EMBEDDED_BY,
            RelationType::PopupFor => atspi_sys::ATSPI_RELATION_POPUP_FOR,
            RelationType::ParentWindowOf => atspi_sys::ATSPI_RELATION_PARENT_WINDOW_OF,
            RelationType::DescriptionFor => atspi_sys::ATSPI_RELATION_DESCRIPTION_FOR,
            RelationType::DescribedBy => atspi_sys::ATSPI_RELATION_DESCRIBED_BY,
            RelationType::Details => atspi_sys::ATSPI_RELATION_DETAILS,
            RelationType::DetailsFor => atspi_sys::ATSPI_RELATION_DETAILS_FOR,
            RelationType::ErrorMessage => atspi_sys::ATSPI_RELATION_ERROR_MESSAGE,
            RelationType::ErrorFor => atspi_sys::ATSPI_RELATION_ERROR_FOR,
            RelationType::LastDefined => atspi_sys::ATSPI_RELATION_LAST_DEFINED,
            RelationType::__Unknown(value) => value
        }
    }
}

#[doc(hidden)]
impl FromGlib<atspi_sys::AtspiRelationType> for RelationType {
    fn from_glib(value: atspi_sys::AtspiRelationType) -> Self {
        skip_assert_initialized!();
        match value {
            0 => RelationType::Null,
            1 => RelationType::LabelFor,
            2 => RelationType::LabelledBy,
            3 => RelationType::ControllerFor,
            4 => RelationType::ControlledBy,
            5 => RelationType::MemberOf,
            6 => RelationType::TooltipFor,
            7 => RelationType::NodeChildOf,
            8 => RelationType::NodeParentOf,
            9 => RelationType::Extended,
            10 => RelationType::FlowsTo,
            11 => RelationType::FlowsFrom,
            12 => RelationType::SubwindowOf,
            13 => RelationType::Embeds,
            14 => RelationType::EmbeddedBy,
            15 => RelationType::PopupFor,
            16 => RelationType::ParentWindowOf,
            17 => RelationType::DescriptionFor,
            18 => RelationType::DescribedBy,
            19 => RelationType::Details,
            20 => RelationType::DetailsFor,
            21 => RelationType::ErrorMessage,
            22 => RelationType::ErrorFor,
            23 => RelationType::LastDefined,
            value => RelationType::__Unknown(value),
        }
    }
}

impl StaticType for RelationType {
    fn static_type() -> Type {
        unsafe { from_glib(atspi_sys::atspi_relation_type_get_type()) }
    }
}

impl<'a> FromValueOptional<'a> for RelationType {
    unsafe fn from_value_optional(value: &Value) -> Option<Self> {
        Some(FromValue::from_value(value))
    }
}

impl<'a> FromValue<'a> for RelationType {
    unsafe fn from_value(value: &Value) -> Self {
        from_glib(gobject_sys::g_value_get_enum(value.to_glib_none().0))
    }
}

impl SetValue for RelationType {
    unsafe fn set_value(value: &mut Value, this: &Self) {
        gobject_sys::g_value_set_enum(value.to_glib_none_mut().0, this.to_glib())
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[derive(Clone, Copy)]
#[non_exhaustive]
pub enum Role {
    Invalid,
    AcceleratorLabel,
    Alert,
    Animation,
    Arrow,
    Calendar,
    Canvas,
    CheckBox,
    CheckMenuItem,
    ColorChooser,
    ColumnHeader,
    ComboBox,
    DateEditor,
    DesktopIcon,
    DesktopFrame,
    Dial,
    Dialog,
    DirectoryPane,
    DrawingArea,
    FileChooser,
    Filler,
    FocusTraversable,
    FontChooser,
    Frame,
    GlassPane,
    HtmlContainer,
    Icon,
    Image,
    InternalFrame,
    Label,
    LayeredPane,
    List,
    ListItem,
    Menu,
    MenuBar,
    MenuItem,
    OptionPane,
    PageTab,
    PageTabList,
    Panel,
    PasswordText,
    PopupMenu,
    ProgressBar,
    PushButton,
    RadioButton,
    RadioMenuItem,
    RootPane,
    RowHeader,
    ScrollBar,
    ScrollPane,
    Separator,
    Slider,
    SpinButton,
    SplitPane,
    StatusBar,
    Table,
    TableCell,
    TableColumnHeader,
    TableRowHeader,
    TearoffMenuItem,
    Terminal,
    Text,
    ToggleButton,
    ToolBar,
    ToolTip,
    Tree,
    TreeTable,
    Unknown,
    Viewport,
    Window,
    Extended,
    Header,
    Footer,
    Paragraph,
    Ruler,
    Application,
    Autocomplete,
    Editbar,
    Embedded,
    Entry,
    Chart,
    Caption,
    DocumentFrame,
    Heading,
    Page,
    Section,
    RedundantObject,
    Form,
    Link,
    InputMethodWindow,
    TableRow,
    TreeItem,
    DocumentSpreadsheet,
    DocumentPresentation,
    DocumentText,
    DocumentWeb,
    DocumentEmail,
    Comment,
    ListBox,
    Grouping,
    ImageMap,
    Notification,
    InfoBar,
    LevelBar,
    TitleBar,
    BlockQuote,
    Audio,
    Video,
    Definition,
    Article,
    Landmark,
    Log,
    Marquee,
    Math,
    Rating,
    Timer,
    Static,
    MathFraction,
    MathRoot,
    Subscript,
    Superscript,
    DescriptionList,
    DescriptionTerm,
    DescriptionValue,
    Footnote,
    ContentDeletion,
    ContentInsertion,
    LastDefined,
    #[doc(hidden)]
    __Unknown(i32),
}

impl fmt::Display for Role {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "Role::{}", match *self {
            Role::Invalid => "Invalid",
            Role::AcceleratorLabel => "AcceleratorLabel",
            Role::Alert => "Alert",
            Role::Animation => "Animation",
            Role::Arrow => "Arrow",
            Role::Calendar => "Calendar",
            Role::Canvas => "Canvas",
            Role::CheckBox => "CheckBox",
            Role::CheckMenuItem => "CheckMenuItem",
            Role::ColorChooser => "ColorChooser",
            Role::ColumnHeader => "ColumnHeader",
            Role::ComboBox => "ComboBox",
            Role::DateEditor => "DateEditor",
            Role::DesktopIcon => "DesktopIcon",
            Role::DesktopFrame => "DesktopFrame",
            Role::Dial => "Dial",
            Role::Dialog => "Dialog",
            Role::DirectoryPane => "DirectoryPane",
            Role::DrawingArea => "DrawingArea",
            Role::FileChooser => "FileChooser",
            Role::Filler => "Filler",
            Role::FocusTraversable => "FocusTraversable",
            Role::FontChooser => "FontChooser",
            Role::Frame => "Frame",
            Role::GlassPane => "GlassPane",
            Role::HtmlContainer => "HtmlContainer",
            Role::Icon => "Icon",
            Role::Image => "Image",
            Role::InternalFrame => "InternalFrame",
            Role::Label => "Label",
            Role::LayeredPane => "LayeredPane",
            Role::List => "List",
            Role::ListItem => "ListItem",
            Role::Menu => "Menu",
            Role::MenuBar => "MenuBar",
            Role::MenuItem => "MenuItem",
            Role::OptionPane => "OptionPane",
            Role::PageTab => "PageTab",
            Role::PageTabList => "PageTabList",
            Role::Panel => "Panel",
            Role::PasswordText => "PasswordText",
            Role::PopupMenu => "PopupMenu",
            Role::ProgressBar => "ProgressBar",
            Role::PushButton => "PushButton",
            Role::RadioButton => "RadioButton",
            Role::RadioMenuItem => "RadioMenuItem",
            Role::RootPane => "RootPane",
            Role::RowHeader => "RowHeader",
            Role::ScrollBar => "ScrollBar",
            Role::ScrollPane => "ScrollPane",
            Role::Separator => "Separator",
            Role::Slider => "Slider",
            Role::SpinButton => "SpinButton",
            Role::SplitPane => "SplitPane",
            Role::StatusBar => "StatusBar",
            Role::Table => "Table",
            Role::TableCell => "TableCell",
            Role::TableColumnHeader => "TableColumnHeader",
            Role::TableRowHeader => "TableRowHeader",
            Role::TearoffMenuItem => "TearoffMenuItem",
            Role::Terminal => "Terminal",
            Role::Text => "Text",
            Role::ToggleButton => "ToggleButton",
            Role::ToolBar => "ToolBar",
            Role::ToolTip => "ToolTip",
            Role::Tree => "Tree",
            Role::TreeTable => "TreeTable",
            Role::Unknown => "Unknown",
            Role::Viewport => "Viewport",
            Role::Window => "Window",
            Role::Extended => "Extended",
            Role::Header => "Header",
            Role::Footer => "Footer",
            Role::Paragraph => "Paragraph",
            Role::Ruler => "Ruler",
            Role::Application => "Application",
            Role::Autocomplete => "Autocomplete",
            Role::Editbar => "Editbar",
            Role::Embedded => "Embedded",
            Role::Entry => "Entry",
            Role::Chart => "Chart",
            Role::Caption => "Caption",
            Role::DocumentFrame => "DocumentFrame",
            Role::Heading => "Heading",
            Role::Page => "Page",
            Role::Section => "Section",
            Role::RedundantObject => "RedundantObject",
            Role::Form => "Form",
            Role::Link => "Link",
            Role::InputMethodWindow => "InputMethodWindow",
            Role::TableRow => "TableRow",
            Role::TreeItem => "TreeItem",
            Role::DocumentSpreadsheet => "DocumentSpreadsheet",
            Role::DocumentPresentation => "DocumentPresentation",
            Role::DocumentText => "DocumentText",
            Role::DocumentWeb => "DocumentWeb",
            Role::DocumentEmail => "DocumentEmail",
            Role::Comment => "Comment",
            Role::ListBox => "ListBox",
            Role::Grouping => "Grouping",
            Role::ImageMap => "ImageMap",
            Role::Notification => "Notification",
            Role::InfoBar => "InfoBar",
            Role::LevelBar => "LevelBar",
            Role::TitleBar => "TitleBar",
            Role::BlockQuote => "BlockQuote",
            Role::Audio => "Audio",
            Role::Video => "Video",
            Role::Definition => "Definition",
            Role::Article => "Article",
            Role::Landmark => "Landmark",
            Role::Log => "Log",
            Role::Marquee => "Marquee",
            Role::Math => "Math",
            Role::Rating => "Rating",
            Role::Timer => "Timer",
            Role::Static => "Static",
            Role::MathFraction => "MathFraction",
            Role::MathRoot => "MathRoot",
            Role::Subscript => "Subscript",
            Role::Superscript => "Superscript",
            Role::DescriptionList => "DescriptionList",
            Role::DescriptionTerm => "DescriptionTerm",
            Role::DescriptionValue => "DescriptionValue",
            Role::Footnote => "Footnote",
            Role::ContentDeletion => "ContentDeletion",
            Role::ContentInsertion => "ContentInsertion",
            Role::LastDefined => "LastDefined",
            _ => "Unknown",
        })
    }
}

#[doc(hidden)]
impl ToGlib for Role {
    type GlibType = atspi_sys::AtspiRole;

    fn to_glib(&self) -> atspi_sys::AtspiRole {
        match *self {
            Role::Invalid => atspi_sys::ATSPI_ROLE_INVALID,
            Role::AcceleratorLabel => atspi_sys::ATSPI_ROLE_ACCELERATOR_LABEL,
            Role::Alert => atspi_sys::ATSPI_ROLE_ALERT,
            Role::Animation => atspi_sys::ATSPI_ROLE_ANIMATION,
            Role::Arrow => atspi_sys::ATSPI_ROLE_ARROW,
            Role::Calendar => atspi_sys::ATSPI_ROLE_CALENDAR,
            Role::Canvas => atspi_sys::ATSPI_ROLE_CANVAS,
            Role::CheckBox => atspi_sys::ATSPI_ROLE_CHECK_BOX,
            Role::CheckMenuItem => atspi_sys::ATSPI_ROLE_CHECK_MENU_ITEM,
            Role::ColorChooser => atspi_sys::ATSPI_ROLE_COLOR_CHOOSER,
            Role::ColumnHeader => atspi_sys::ATSPI_ROLE_COLUMN_HEADER,
            Role::ComboBox => atspi_sys::ATSPI_ROLE_COMBO_BOX,
            Role::DateEditor => atspi_sys::ATSPI_ROLE_DATE_EDITOR,
            Role::DesktopIcon => atspi_sys::ATSPI_ROLE_DESKTOP_ICON,
            Role::DesktopFrame => atspi_sys::ATSPI_ROLE_DESKTOP_FRAME,
            Role::Dial => atspi_sys::ATSPI_ROLE_DIAL,
            Role::Dialog => atspi_sys::ATSPI_ROLE_DIALOG,
            Role::DirectoryPane => atspi_sys::ATSPI_ROLE_DIRECTORY_PANE,
            Role::DrawingArea => atspi_sys::ATSPI_ROLE_DRAWING_AREA,
            Role::FileChooser => atspi_sys::ATSPI_ROLE_FILE_CHOOSER,
            Role::Filler => atspi_sys::ATSPI_ROLE_FILLER,
            Role::FocusTraversable => atspi_sys::ATSPI_ROLE_FOCUS_TRAVERSABLE,
            Role::FontChooser => atspi_sys::ATSPI_ROLE_FONT_CHOOSER,
            Role::Frame => atspi_sys::ATSPI_ROLE_FRAME,
            Role::GlassPane => atspi_sys::ATSPI_ROLE_GLASS_PANE,
            Role::HtmlContainer => atspi_sys::ATSPI_ROLE_HTML_CONTAINER,
            Role::Icon => atspi_sys::ATSPI_ROLE_ICON,
            Role::Image => atspi_sys::ATSPI_ROLE_IMAGE,
            Role::InternalFrame => atspi_sys::ATSPI_ROLE_INTERNAL_FRAME,
            Role::Label => atspi_sys::ATSPI_ROLE_LABEL,
            Role::LayeredPane => atspi_sys::ATSPI_ROLE_LAYERED_PANE,
            Role::List => atspi_sys::ATSPI_ROLE_LIST,
            Role::ListItem => atspi_sys::ATSPI_ROLE_LIST_ITEM,
            Role::Menu => atspi_sys::ATSPI_ROLE_MENU,
            Role::MenuBar => atspi_sys::ATSPI_ROLE_MENU_BAR,
            Role::MenuItem => atspi_sys::ATSPI_ROLE_MENU_ITEM,
            Role::OptionPane => atspi_sys::ATSPI_ROLE_OPTION_PANE,
            Role::PageTab => atspi_sys::ATSPI_ROLE_PAGE_TAB,
            Role::PageTabList => atspi_sys::ATSPI_ROLE_PAGE_TAB_LIST,
            Role::Panel => atspi_sys::ATSPI_ROLE_PANEL,
            Role::PasswordText => atspi_sys::ATSPI_ROLE_PASSWORD_TEXT,
            Role::PopupMenu => atspi_sys::ATSPI_ROLE_POPUP_MENU,
            Role::ProgressBar => atspi_sys::ATSPI_ROLE_PROGRESS_BAR,
            Role::PushButton => atspi_sys::ATSPI_ROLE_PUSH_BUTTON,
            Role::RadioButton => atspi_sys::ATSPI_ROLE_RADIO_BUTTON,
            Role::RadioMenuItem => atspi_sys::ATSPI_ROLE_RADIO_MENU_ITEM,
            Role::RootPane => atspi_sys::ATSPI_ROLE_ROOT_PANE,
            Role::RowHeader => atspi_sys::ATSPI_ROLE_ROW_HEADER,
            Role::ScrollBar => atspi_sys::ATSPI_ROLE_SCROLL_BAR,
            Role::ScrollPane => atspi_sys::ATSPI_ROLE_SCROLL_PANE,
            Role::Separator => atspi_sys::ATSPI_ROLE_SEPARATOR,
            Role::Slider => atspi_sys::ATSPI_ROLE_SLIDER,
            Role::SpinButton => atspi_sys::ATSPI_ROLE_SPIN_BUTTON,
            Role::SplitPane => atspi_sys::ATSPI_ROLE_SPLIT_PANE,
            Role::StatusBar => atspi_sys::ATSPI_ROLE_STATUS_BAR,
            Role::Table => atspi_sys::ATSPI_ROLE_TABLE,
            Role::TableCell => atspi_sys::ATSPI_ROLE_TABLE_CELL,
            Role::TableColumnHeader => atspi_sys::ATSPI_ROLE_TABLE_COLUMN_HEADER,
            Role::TableRowHeader => atspi_sys::ATSPI_ROLE_TABLE_ROW_HEADER,
            Role::TearoffMenuItem => atspi_sys::ATSPI_ROLE_TEAROFF_MENU_ITEM,
            Role::Terminal => atspi_sys::ATSPI_ROLE_TERMINAL,
            Role::Text => atspi_sys::ATSPI_ROLE_TEXT,
            Role::ToggleButton => atspi_sys::ATSPI_ROLE_TOGGLE_BUTTON,
            Role::ToolBar => atspi_sys::ATSPI_ROLE_TOOL_BAR,
            Role::ToolTip => atspi_sys::ATSPI_ROLE_TOOL_TIP,
            Role::Tree => atspi_sys::ATSPI_ROLE_TREE,
            Role::TreeTable => atspi_sys::ATSPI_ROLE_TREE_TABLE,
            Role::Unknown => atspi_sys::ATSPI_ROLE_UNKNOWN,
            Role::Viewport => atspi_sys::ATSPI_ROLE_VIEWPORT,
            Role::Window => atspi_sys::ATSPI_ROLE_WINDOW,
            Role::Extended => atspi_sys::ATSPI_ROLE_EXTENDED,
            Role::Header => atspi_sys::ATSPI_ROLE_HEADER,
            Role::Footer => atspi_sys::ATSPI_ROLE_FOOTER,
            Role::Paragraph => atspi_sys::ATSPI_ROLE_PARAGRAPH,
            Role::Ruler => atspi_sys::ATSPI_ROLE_RULER,
            Role::Application => atspi_sys::ATSPI_ROLE_APPLICATION,
            Role::Autocomplete => atspi_sys::ATSPI_ROLE_AUTOCOMPLETE,
            Role::Editbar => atspi_sys::ATSPI_ROLE_EDITBAR,
            Role::Embedded => atspi_sys::ATSPI_ROLE_EMBEDDED,
            Role::Entry => atspi_sys::ATSPI_ROLE_ENTRY,
            Role::Chart => atspi_sys::ATSPI_ROLE_CHART,
            Role::Caption => atspi_sys::ATSPI_ROLE_CAPTION,
            Role::DocumentFrame => atspi_sys::ATSPI_ROLE_DOCUMENT_FRAME,
            Role::Heading => atspi_sys::ATSPI_ROLE_HEADING,
            Role::Page => atspi_sys::ATSPI_ROLE_PAGE,
            Role::Section => atspi_sys::ATSPI_ROLE_SECTION,
            Role::RedundantObject => atspi_sys::ATSPI_ROLE_REDUNDANT_OBJECT,
            Role::Form => atspi_sys::ATSPI_ROLE_FORM,
            Role::Link => atspi_sys::ATSPI_ROLE_LINK,
            Role::InputMethodWindow => atspi_sys::ATSPI_ROLE_INPUT_METHOD_WINDOW,
            Role::TableRow => atspi_sys::ATSPI_ROLE_TABLE_ROW,
            Role::TreeItem => atspi_sys::ATSPI_ROLE_TREE_ITEM,
            Role::DocumentSpreadsheet => atspi_sys::ATSPI_ROLE_DOCUMENT_SPREADSHEET,
            Role::DocumentPresentation => atspi_sys::ATSPI_ROLE_DOCUMENT_PRESENTATION,
            Role::DocumentText => atspi_sys::ATSPI_ROLE_DOCUMENT_TEXT,
            Role::DocumentWeb => atspi_sys::ATSPI_ROLE_DOCUMENT_WEB,
            Role::DocumentEmail => atspi_sys::ATSPI_ROLE_DOCUMENT_EMAIL,
            Role::Comment => atspi_sys::ATSPI_ROLE_COMMENT,
            Role::ListBox => atspi_sys::ATSPI_ROLE_LIST_BOX,
            Role::Grouping => atspi_sys::ATSPI_ROLE_GROUPING,
            Role::ImageMap => atspi_sys::ATSPI_ROLE_IMAGE_MAP,
            Role::Notification => atspi_sys::ATSPI_ROLE_NOTIFICATION,
            Role::InfoBar => atspi_sys::ATSPI_ROLE_INFO_BAR,
            Role::LevelBar => atspi_sys::ATSPI_ROLE_LEVEL_BAR,
            Role::TitleBar => atspi_sys::ATSPI_ROLE_TITLE_BAR,
            Role::BlockQuote => atspi_sys::ATSPI_ROLE_BLOCK_QUOTE,
            Role::Audio => atspi_sys::ATSPI_ROLE_AUDIO,
            Role::Video => atspi_sys::ATSPI_ROLE_VIDEO,
            Role::Definition => atspi_sys::ATSPI_ROLE_DEFINITION,
            Role::Article => atspi_sys::ATSPI_ROLE_ARTICLE,
            Role::Landmark => atspi_sys::ATSPI_ROLE_LANDMARK,
            Role::Log => atspi_sys::ATSPI_ROLE_LOG,
            Role::Marquee => atspi_sys::ATSPI_ROLE_MARQUEE,
            Role::Math => atspi_sys::ATSPI_ROLE_MATH,
            Role::Rating => atspi_sys::ATSPI_ROLE_RATING,
            Role::Timer => atspi_sys::ATSPI_ROLE_TIMER,
            Role::Static => atspi_sys::ATSPI_ROLE_STATIC,
            Role::MathFraction => atspi_sys::ATSPI_ROLE_MATH_FRACTION,
            Role::MathRoot => atspi_sys::ATSPI_ROLE_MATH_ROOT,
            Role::Subscript => atspi_sys::ATSPI_ROLE_SUBSCRIPT,
            Role::Superscript => atspi_sys::ATSPI_ROLE_SUPERSCRIPT,
            Role::DescriptionList => atspi_sys::ATSPI_ROLE_DESCRIPTION_LIST,
            Role::DescriptionTerm => atspi_sys::ATSPI_ROLE_DESCRIPTION_TERM,
            Role::DescriptionValue => atspi_sys::ATSPI_ROLE_DESCRIPTION_VALUE,
            Role::Footnote => atspi_sys::ATSPI_ROLE_FOOTNOTE,
            Role::ContentDeletion => atspi_sys::ATSPI_ROLE_CONTENT_DELETION,
            Role::ContentInsertion => atspi_sys::ATSPI_ROLE_CONTENT_INSERTION,
            Role::LastDefined => atspi_sys::ATSPI_ROLE_LAST_DEFINED,
            Role::__Unknown(value) => value
        }
    }
}

#[doc(hidden)]
impl FromGlib<atspi_sys::AtspiRole> for Role {
    fn from_glib(value: atspi_sys::AtspiRole) -> Self {
        skip_assert_initialized!();
        match value {
            0 => Role::Invalid,
            1 => Role::AcceleratorLabel,
            2 => Role::Alert,
            3 => Role::Animation,
            4 => Role::Arrow,
            5 => Role::Calendar,
            6 => Role::Canvas,
            7 => Role::CheckBox,
            8 => Role::CheckMenuItem,
            9 => Role::ColorChooser,
            10 => Role::ColumnHeader,
            11 => Role::ComboBox,
            12 => Role::DateEditor,
            13 => Role::DesktopIcon,
            14 => Role::DesktopFrame,
            15 => Role::Dial,
            16 => Role::Dialog,
            17 => Role::DirectoryPane,
            18 => Role::DrawingArea,
            19 => Role::FileChooser,
            20 => Role::Filler,
            21 => Role::FocusTraversable,
            22 => Role::FontChooser,
            23 => Role::Frame,
            24 => Role::GlassPane,
            25 => Role::HtmlContainer,
            26 => Role::Icon,
            27 => Role::Image,
            28 => Role::InternalFrame,
            29 => Role::Label,
            30 => Role::LayeredPane,
            31 => Role::List,
            32 => Role::ListItem,
            33 => Role::Menu,
            34 => Role::MenuBar,
            35 => Role::MenuItem,
            36 => Role::OptionPane,
            37 => Role::PageTab,
            38 => Role::PageTabList,
            39 => Role::Panel,
            40 => Role::PasswordText,
            41 => Role::PopupMenu,
            42 => Role::ProgressBar,
            43 => Role::PushButton,
            44 => Role::RadioButton,
            45 => Role::RadioMenuItem,
            46 => Role::RootPane,
            47 => Role::RowHeader,
            48 => Role::ScrollBar,
            49 => Role::ScrollPane,
            50 => Role::Separator,
            51 => Role::Slider,
            52 => Role::SpinButton,
            53 => Role::SplitPane,
            54 => Role::StatusBar,
            55 => Role::Table,
            56 => Role::TableCell,
            57 => Role::TableColumnHeader,
            58 => Role::TableRowHeader,
            59 => Role::TearoffMenuItem,
            60 => Role::Terminal,
            61 => Role::Text,
            62 => Role::ToggleButton,
            63 => Role::ToolBar,
            64 => Role::ToolTip,
            65 => Role::Tree,
            66 => Role::TreeTable,
            67 => Role::Unknown,
            68 => Role::Viewport,
            69 => Role::Window,
            70 => Role::Extended,
            71 => Role::Header,
            72 => Role::Footer,
            73 => Role::Paragraph,
            74 => Role::Ruler,
            75 => Role::Application,
            76 => Role::Autocomplete,
            77 => Role::Editbar,
            78 => Role::Embedded,
            79 => Role::Entry,
            80 => Role::Chart,
            81 => Role::Caption,
            82 => Role::DocumentFrame,
            83 => Role::Heading,
            84 => Role::Page,
            85 => Role::Section,
            86 => Role::RedundantObject,
            87 => Role::Form,
            88 => Role::Link,
            89 => Role::InputMethodWindow,
            90 => Role::TableRow,
            91 => Role::TreeItem,
            92 => Role::DocumentSpreadsheet,
            93 => Role::DocumentPresentation,
            94 => Role::DocumentText,
            95 => Role::DocumentWeb,
            96 => Role::DocumentEmail,
            97 => Role::Comment,
            98 => Role::ListBox,
            99 => Role::Grouping,
            100 => Role::ImageMap,
            101 => Role::Notification,
            102 => Role::InfoBar,
            103 => Role::LevelBar,
            104 => Role::TitleBar,
            105 => Role::BlockQuote,
            106 => Role::Audio,
            107 => Role::Video,
            108 => Role::Definition,
            109 => Role::Article,
            110 => Role::Landmark,
            111 => Role::Log,
            112 => Role::Marquee,
            113 => Role::Math,
            114 => Role::Rating,
            115 => Role::Timer,
            116 => Role::Static,
            117 => Role::MathFraction,
            118 => Role::MathRoot,
            119 => Role::Subscript,
            120 => Role::Superscript,
            121 => Role::DescriptionList,
            122 => Role::DescriptionTerm,
            123 => Role::DescriptionValue,
            124 => Role::Footnote,
            125 => Role::ContentDeletion,
            126 => Role::ContentInsertion,
            127 => Role::LastDefined,
            value => Role::__Unknown(value),
        }
    }
}

impl StaticType for Role {
    fn static_type() -> Type {
        unsafe { from_glib(atspi_sys::atspi_role_get_type()) }
    }
}

impl<'a> FromValueOptional<'a> for Role {
    unsafe fn from_value_optional(value: &Value) -> Option<Self> {
        Some(FromValue::from_value(value))
    }
}

impl<'a> FromValue<'a> for Role {
    unsafe fn from_value(value: &Value) -> Self {
        from_glib(gobject_sys::g_value_get_enum(value.to_glib_none().0))
    }
}

impl SetValue for Role {
    unsafe fn set_value(value: &mut Value, this: &Self) {
        gobject_sys::g_value_set_enum(value.to_glib_none_mut().0, this.to_glib())
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[derive(Clone, Copy)]
#[non_exhaustive]
pub enum StateType {
    Invalid,
    Active,
    Armed,
    Busy,
    Checked,
    Collapsed,
    Defunct,
    Editable,
    Enabled,
    Expandable,
    Expanded,
    Focusable,
    Focused,
    HasTooltip,
    Horizontal,
    Iconified,
    Modal,
    MultiLine,
    Multiselectable,
    Opaque,
    Pressed,
    Resizable,
    Selectable,
    Selected,
    Sensitive,
    Showing,
    SingleLine,
    Stale,
    Transient,
    Vertical,
    Visible,
    ManagesDescendants,
    Indeterminate,
    Required,
    Truncated,
    Animated,
    InvalidEntry,
    SupportsAutocompletion,
    SelectableText,
    IsDefault,
    Visited,
    Checkable,
    HasPopup,
    ReadOnly,
    LastDefined,
    #[doc(hidden)]
    __Unknown(i32),
}

impl fmt::Display for StateType {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "StateType::{}", match *self {
            StateType::Invalid => "Invalid",
            StateType::Active => "Active",
            StateType::Armed => "Armed",
            StateType::Busy => "Busy",
            StateType::Checked => "Checked",
            StateType::Collapsed => "Collapsed",
            StateType::Defunct => "Defunct",
            StateType::Editable => "Editable",
            StateType::Enabled => "Enabled",
            StateType::Expandable => "Expandable",
            StateType::Expanded => "Expanded",
            StateType::Focusable => "Focusable",
            StateType::Focused => "Focused",
            StateType::HasTooltip => "HasTooltip",
            StateType::Horizontal => "Horizontal",
            StateType::Iconified => "Iconified",
            StateType::Modal => "Modal",
            StateType::MultiLine => "MultiLine",
            StateType::Multiselectable => "Multiselectable",
            StateType::Opaque => "Opaque",
            StateType::Pressed => "Pressed",
            StateType::Resizable => "Resizable",
            StateType::Selectable => "Selectable",
            StateType::Selected => "Selected",
            StateType::Sensitive => "Sensitive",
            StateType::Showing => "Showing",
            StateType::SingleLine => "SingleLine",
            StateType::Stale => "Stale",
            StateType::Transient => "Transient",
            StateType::Vertical => "Vertical",
            StateType::Visible => "Visible",
            StateType::ManagesDescendants => "ManagesDescendants",
            StateType::Indeterminate => "Indeterminate",
            StateType::Required => "Required",
            StateType::Truncated => "Truncated",
            StateType::Animated => "Animated",
            StateType::InvalidEntry => "InvalidEntry",
            StateType::SupportsAutocompletion => "SupportsAutocompletion",
            StateType::SelectableText => "SelectableText",
            StateType::IsDefault => "IsDefault",
            StateType::Visited => "Visited",
            StateType::Checkable => "Checkable",
            StateType::HasPopup => "HasPopup",
            StateType::ReadOnly => "ReadOnly",
            StateType::LastDefined => "LastDefined",
            _ => "Unknown",
        })
    }
}

#[doc(hidden)]
impl ToGlib for StateType {
    type GlibType = atspi_sys::AtspiStateType;

    fn to_glib(&self) -> atspi_sys::AtspiStateType {
        match *self {
            StateType::Invalid => atspi_sys::ATSPI_STATE_INVALID,
            StateType::Active => atspi_sys::ATSPI_STATE_ACTIVE,
            StateType::Armed => atspi_sys::ATSPI_STATE_ARMED,
            StateType::Busy => atspi_sys::ATSPI_STATE_BUSY,
            StateType::Checked => atspi_sys::ATSPI_STATE_CHECKED,
            StateType::Collapsed => atspi_sys::ATSPI_STATE_COLLAPSED,
            StateType::Defunct => atspi_sys::ATSPI_STATE_DEFUNCT,
            StateType::Editable => atspi_sys::ATSPI_STATE_EDITABLE,
            StateType::Enabled => atspi_sys::ATSPI_STATE_ENABLED,
            StateType::Expandable => atspi_sys::ATSPI_STATE_EXPANDABLE,
            StateType::Expanded => atspi_sys::ATSPI_STATE_EXPANDED,
            StateType::Focusable => atspi_sys::ATSPI_STATE_FOCUSABLE,
            StateType::Focused => atspi_sys::ATSPI_STATE_FOCUSED,
            StateType::HasTooltip => atspi_sys::ATSPI_STATE_HAS_TOOLTIP,
            StateType::Horizontal => atspi_sys::ATSPI_STATE_HORIZONTAL,
            StateType::Iconified => atspi_sys::ATSPI_STATE_ICONIFIED,
            StateType::Modal => atspi_sys::ATSPI_STATE_MODAL,
            StateType::MultiLine => atspi_sys::ATSPI_STATE_MULTI_LINE,
            StateType::Multiselectable => atspi_sys::ATSPI_STATE_MULTISELECTABLE,
            StateType::Opaque => atspi_sys::ATSPI_STATE_OPAQUE,
            StateType::Pressed => atspi_sys::ATSPI_STATE_PRESSED,
            StateType::Resizable => atspi_sys::ATSPI_STATE_RESIZABLE,
            StateType::Selectable => atspi_sys::ATSPI_STATE_SELECTABLE,
            StateType::Selected => atspi_sys::ATSPI_STATE_SELECTED,
            StateType::Sensitive => atspi_sys::ATSPI_STATE_SENSITIVE,
            StateType::Showing => atspi_sys::ATSPI_STATE_SHOWING,
            StateType::SingleLine => atspi_sys::ATSPI_STATE_SINGLE_LINE,
            StateType::Stale => atspi_sys::ATSPI_STATE_STALE,
            StateType::Transient => atspi_sys::ATSPI_STATE_TRANSIENT,
            StateType::Vertical => atspi_sys::ATSPI_STATE_VERTICAL,
            StateType::Visible => atspi_sys::ATSPI_STATE_VISIBLE,
            StateType::ManagesDescendants => atspi_sys::ATSPI_STATE_MANAGES_DESCENDANTS,
            StateType::Indeterminate => atspi_sys::ATSPI_STATE_INDETERMINATE,
            StateType::Required => atspi_sys::ATSPI_STATE_REQUIRED,
            StateType::Truncated => atspi_sys::ATSPI_STATE_TRUNCATED,
            StateType::Animated => atspi_sys::ATSPI_STATE_ANIMATED,
            StateType::InvalidEntry => atspi_sys::ATSPI_STATE_INVALID_ENTRY,
            StateType::SupportsAutocompletion => atspi_sys::ATSPI_STATE_SUPPORTS_AUTOCOMPLETION,
            StateType::SelectableText => atspi_sys::ATSPI_STATE_SELECTABLE_TEXT,
            StateType::IsDefault => atspi_sys::ATSPI_STATE_IS_DEFAULT,
            StateType::Visited => atspi_sys::ATSPI_STATE_VISITED,
            StateType::Checkable => atspi_sys::ATSPI_STATE_CHECKABLE,
            StateType::HasPopup => atspi_sys::ATSPI_STATE_HAS_POPUP,
            StateType::ReadOnly => atspi_sys::ATSPI_STATE_READ_ONLY,
            StateType::LastDefined => atspi_sys::ATSPI_STATE_LAST_DEFINED,
            StateType::__Unknown(value) => value
        }
    }
}

#[doc(hidden)]
impl FromGlib<atspi_sys::AtspiStateType> for StateType {
    fn from_glib(value: atspi_sys::AtspiStateType) -> Self {
        skip_assert_initialized!();
        match value {
            0 => StateType::Invalid,
            1 => StateType::Active,
            2 => StateType::Armed,
            3 => StateType::Busy,
            4 => StateType::Checked,
            5 => StateType::Collapsed,
            6 => StateType::Defunct,
            7 => StateType::Editable,
            8 => StateType::Enabled,
            9 => StateType::Expandable,
            10 => StateType::Expanded,
            11 => StateType::Focusable,
            12 => StateType::Focused,
            13 => StateType::HasTooltip,
            14 => StateType::Horizontal,
            15 => StateType::Iconified,
            16 => StateType::Modal,
            17 => StateType::MultiLine,
            18 => StateType::Multiselectable,
            19 => StateType::Opaque,
            20 => StateType::Pressed,
            21 => StateType::Resizable,
            22 => StateType::Selectable,
            23 => StateType::Selected,
            24 => StateType::Sensitive,
            25 => StateType::Showing,
            26 => StateType::SingleLine,
            27 => StateType::Stale,
            28 => StateType::Transient,
            29 => StateType::Vertical,
            30 => StateType::Visible,
            31 => StateType::ManagesDescendants,
            32 => StateType::Indeterminate,
            33 => StateType::Required,
            34 => StateType::Truncated,
            35 => StateType::Animated,
            36 => StateType::InvalidEntry,
            37 => StateType::SupportsAutocompletion,
            38 => StateType::SelectableText,
            39 => StateType::IsDefault,
            40 => StateType::Visited,
            41 => StateType::Checkable,
            42 => StateType::HasPopup,
            43 => StateType::ReadOnly,
            44 => StateType::LastDefined,
            value => StateType::__Unknown(value),
        }
    }
}

impl StaticType for StateType {
    fn static_type() -> Type {
        unsafe { from_glib(atspi_sys::atspi_state_type_get_type()) }
    }
}

impl<'a> FromValueOptional<'a> for StateType {
    unsafe fn from_value_optional(value: &Value) -> Option<Self> {
        Some(FromValue::from_value(value))
    }
}

impl<'a> FromValue<'a> for StateType {
    unsafe fn from_value(value: &Value) -> Self {
        from_glib(gobject_sys::g_value_get_enum(value.to_glib_none().0))
    }
}

impl SetValue for StateType {
    unsafe fn set_value(value: &mut Value, this: &Self) {
        gobject_sys::g_value_set_enum(value.to_glib_none_mut().0, this.to_glib())
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[derive(Clone, Copy)]
#[non_exhaustive]
pub enum TextBoundaryType {
    Char,
    WordStart,
    WordEnd,
    SentenceStart,
    SentenceEnd,
    LineStart,
    LineEnd,
    #[doc(hidden)]
    __Unknown(i32),
}

impl fmt::Display for TextBoundaryType {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "TextBoundaryType::{}", match *self {
            TextBoundaryType::Char => "Char",
            TextBoundaryType::WordStart => "WordStart",
            TextBoundaryType::WordEnd => "WordEnd",
            TextBoundaryType::SentenceStart => "SentenceStart",
            TextBoundaryType::SentenceEnd => "SentenceEnd",
            TextBoundaryType::LineStart => "LineStart",
            TextBoundaryType::LineEnd => "LineEnd",
            _ => "Unknown",
        })
    }
}

#[doc(hidden)]
impl ToGlib for TextBoundaryType {
    type GlibType = atspi_sys::AtspiTextBoundaryType;

    fn to_glib(&self) -> atspi_sys::AtspiTextBoundaryType {
        match *self {
            TextBoundaryType::Char => atspi_sys::ATSPI_TEXT_BOUNDARY_CHAR,
            TextBoundaryType::WordStart => atspi_sys::ATSPI_TEXT_BOUNDARY_WORD_START,
            TextBoundaryType::WordEnd => atspi_sys::ATSPI_TEXT_BOUNDARY_WORD_END,
            TextBoundaryType::SentenceStart => atspi_sys::ATSPI_TEXT_BOUNDARY_SENTENCE_START,
            TextBoundaryType::SentenceEnd => atspi_sys::ATSPI_TEXT_BOUNDARY_SENTENCE_END,
            TextBoundaryType::LineStart => atspi_sys::ATSPI_TEXT_BOUNDARY_LINE_START,
            TextBoundaryType::LineEnd => atspi_sys::ATSPI_TEXT_BOUNDARY_LINE_END,
            TextBoundaryType::__Unknown(value) => value
        }
    }
}

#[doc(hidden)]
impl FromGlib<atspi_sys::AtspiTextBoundaryType> for TextBoundaryType {
    fn from_glib(value: atspi_sys::AtspiTextBoundaryType) -> Self {
        skip_assert_initialized!();
        match value {
            0 => TextBoundaryType::Char,
            1 => TextBoundaryType::WordStart,
            2 => TextBoundaryType::WordEnd,
            3 => TextBoundaryType::SentenceStart,
            4 => TextBoundaryType::SentenceEnd,
            5 => TextBoundaryType::LineStart,
            6 => TextBoundaryType::LineEnd,
            value => TextBoundaryType::__Unknown(value),
        }
    }
}

impl StaticType for TextBoundaryType {
    fn static_type() -> Type {
        unsafe { from_glib(atspi_sys::atspi_text_boundary_type_get_type()) }
    }
}

impl<'a> FromValueOptional<'a> for TextBoundaryType {
    unsafe fn from_value_optional(value: &Value) -> Option<Self> {
        Some(FromValue::from_value(value))
    }
}

impl<'a> FromValue<'a> for TextBoundaryType {
    unsafe fn from_value(value: &Value) -> Self {
        from_glib(gobject_sys::g_value_get_enum(value.to_glib_none().0))
    }
}

impl SetValue for TextBoundaryType {
    unsafe fn set_value(value: &mut Value, this: &Self) {
        gobject_sys::g_value_set_enum(value.to_glib_none_mut().0, this.to_glib())
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[derive(Clone, Copy)]
#[non_exhaustive]
pub enum TextClipType {
    None,
    Min,
    Max,
    Both,
    #[doc(hidden)]
    __Unknown(i32),
}

impl fmt::Display for TextClipType {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "TextClipType::{}", match *self {
            TextClipType::None => "None",
            TextClipType::Min => "Min",
            TextClipType::Max => "Max",
            TextClipType::Both => "Both",
            _ => "Unknown",
        })
    }
}

#[doc(hidden)]
impl ToGlib for TextClipType {
    type GlibType = atspi_sys::AtspiTextClipType;

    fn to_glib(&self) -> atspi_sys::AtspiTextClipType {
        match *self {
            TextClipType::None => atspi_sys::ATSPI_TEXT_CLIP_NONE,
            TextClipType::Min => atspi_sys::ATSPI_TEXT_CLIP_MIN,
            TextClipType::Max => atspi_sys::ATSPI_TEXT_CLIP_MAX,
            TextClipType::Both => atspi_sys::ATSPI_TEXT_CLIP_BOTH,
            TextClipType::__Unknown(value) => value
        }
    }
}

#[doc(hidden)]
impl FromGlib<atspi_sys::AtspiTextClipType> for TextClipType {
    fn from_glib(value: atspi_sys::AtspiTextClipType) -> Self {
        skip_assert_initialized!();
        match value {
            0 => TextClipType::None,
            1 => TextClipType::Min,
            2 => TextClipType::Max,
            3 => TextClipType::Both,
            value => TextClipType::__Unknown(value),
        }
    }
}

impl StaticType for TextClipType {
    fn static_type() -> Type {
        unsafe { from_glib(atspi_sys::atspi_text_clip_type_get_type()) }
    }
}

impl<'a> FromValueOptional<'a> for TextClipType {
    unsafe fn from_value_optional(value: &Value) -> Option<Self> {
        Some(FromValue::from_value(value))
    }
}

impl<'a> FromValue<'a> for TextClipType {
    unsafe fn from_value(value: &Value) -> Self {
        from_glib(gobject_sys::g_value_get_enum(value.to_glib_none().0))
    }
}

impl SetValue for TextClipType {
    unsafe fn set_value(value: &mut Value, this: &Self) {
        gobject_sys::g_value_set_enum(value.to_glib_none_mut().0, this.to_glib())
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[derive(Clone, Copy)]
#[non_exhaustive]
pub enum TextGranularity {
    Char,
    Word,
    Sentence,
    Line,
    Paragraph,
    #[doc(hidden)]
    __Unknown(i32),
}

impl fmt::Display for TextGranularity {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "TextGranularity::{}", match *self {
            TextGranularity::Char => "Char",
            TextGranularity::Word => "Word",
            TextGranularity::Sentence => "Sentence",
            TextGranularity::Line => "Line",
            TextGranularity::Paragraph => "Paragraph",
            _ => "Unknown",
        })
    }
}

#[doc(hidden)]
impl ToGlib for TextGranularity {
    type GlibType = atspi_sys::AtspiTextGranularity;

    fn to_glib(&self) -> atspi_sys::AtspiTextGranularity {
        match *self {
            TextGranularity::Char => atspi_sys::ATSPI_TEXT_GRANULARITY_CHAR,
            TextGranularity::Word => atspi_sys::ATSPI_TEXT_GRANULARITY_WORD,
            TextGranularity::Sentence => atspi_sys::ATSPI_TEXT_GRANULARITY_SENTENCE,
            TextGranularity::Line => atspi_sys::ATSPI_TEXT_GRANULARITY_LINE,
            TextGranularity::Paragraph => atspi_sys::ATSPI_TEXT_GRANULARITY_PARAGRAPH,
            TextGranularity::__Unknown(value) => value
        }
    }
}

#[doc(hidden)]
impl FromGlib<atspi_sys::AtspiTextGranularity> for TextGranularity {
    fn from_glib(value: atspi_sys::AtspiTextGranularity) -> Self {
        skip_assert_initialized!();
        match value {
            0 => TextGranularity::Char,
            1 => TextGranularity::Word,
            2 => TextGranularity::Sentence,
            3 => TextGranularity::Line,
            4 => TextGranularity::Paragraph,
            value => TextGranularity::__Unknown(value),
        }
    }
}

impl StaticType for TextGranularity {
    fn static_type() -> Type {
        unsafe { from_glib(atspi_sys::atspi_text_granularity_get_type()) }
    }
}

impl<'a> FromValueOptional<'a> for TextGranularity {
    unsafe fn from_value_optional(value: &Value) -> Option<Self> {
        Some(FromValue::from_value(value))
    }
}

impl<'a> FromValue<'a> for TextGranularity {
    unsafe fn from_value(value: &Value) -> Self {
        from_glib(gobject_sys::g_value_get_enum(value.to_glib_none().0))
    }
}

impl SetValue for TextGranularity {
    unsafe fn set_value(value: &mut Value, this: &Self) {
        gobject_sys::g_value_set_enum(value.to_glib_none_mut().0, this.to_glib())
    }
}

