// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use atspi_sys;
use glib::StaticType;
use glib::Type;
use glib::translate::*;
use glib::value::FromValue;
use glib::value::FromValueOptional;
use glib::value::SetValue;
use glib::value::Value;
use gobject_sys;
use std::fmt;

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[derive(Clone, Copy)]
pub enum CollectionSortOrder {
    Invalid,
    Canonical,
    Flow,
    Tab,
    ReverseCanonical,
    ReverseFlow,
    ReverseTab,
    LastDefined,
    #[doc(hidden)]
    __Unknown(i32),
}

impl fmt::Display for CollectionSortOrder {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "CollectionSortOrder::{}", match *self {
            CollectionSortOrder::Invalid => "Invalid",
            CollectionSortOrder::Canonical => "Canonical",
            CollectionSortOrder::Flow => "Flow",
            CollectionSortOrder::Tab => "Tab",
            CollectionSortOrder::ReverseCanonical => "ReverseCanonical",
            CollectionSortOrder::ReverseFlow => "ReverseFlow",
            CollectionSortOrder::ReverseTab => "ReverseTab",
            CollectionSortOrder::LastDefined => "LastDefined",
            _ => "Unknown",
        })
    }
}

#[doc(hidden)]
impl ToGlib for CollectionSortOrder {
    type GlibType = atspi_sys::AtspiCollectionSortOrder;

    fn to_glib(&self) -> atspi_sys::AtspiCollectionSortOrder {
        match *self {
            CollectionSortOrder::Invalid => atspi_sys::ATSPI_Collection_SORT_ORDER_INVALID,
            CollectionSortOrder::Canonical => atspi_sys::ATSPI_Collection_SORT_ORDER_CANONICAL,
            CollectionSortOrder::Flow => atspi_sys::ATSPI_Collection_SORT_ORDER_FLOW,
            CollectionSortOrder::Tab => atspi_sys::ATSPI_Collection_SORT_ORDER_TAB,
            CollectionSortOrder::ReverseCanonical => atspi_sys::ATSPI_Collection_SORT_ORDER_REVERSE_CANONICAL,
            CollectionSortOrder::ReverseFlow => atspi_sys::ATSPI_Collection_SORT_ORDER_REVERSE_FLOW,
            CollectionSortOrder::ReverseTab => atspi_sys::ATSPI_Collection_SORT_ORDER_REVERSE_TAB,
            CollectionSortOrder::LastDefined => atspi_sys::ATSPI_Collection_SORT_ORDER_LAST_DEFINED,
            CollectionSortOrder::__Unknown(value) => value
        }
    }
}

#[doc(hidden)]
impl FromGlib<atspi_sys::AtspiCollectionSortOrder> for CollectionSortOrder {
    fn from_glib(value: atspi_sys::AtspiCollectionSortOrder) -> Self {
        skip_assert_initialized!();
        match value {
            0 => CollectionSortOrder::Invalid,
            1 => CollectionSortOrder::Canonical,
            2 => CollectionSortOrder::Flow,
            3 => CollectionSortOrder::Tab,
            4 => CollectionSortOrder::ReverseCanonical,
            5 => CollectionSortOrder::ReverseFlow,
            6 => CollectionSortOrder::ReverseTab,
            7 => CollectionSortOrder::LastDefined,
            value => CollectionSortOrder::__Unknown(value),
        }
    }
}

impl StaticType for CollectionSortOrder {
    fn static_type() -> Type {
        unsafe { from_glib(atspi_sys::atspi_collection_sort_order_get_type()) }
    }
}

impl<'a> FromValueOptional<'a> for CollectionSortOrder {
    unsafe fn from_value_optional(value: &Value) -> Option<Self> {
        Some(FromValue::from_value(value))
    }
}

impl<'a> FromValue<'a> for CollectionSortOrder {
    unsafe fn from_value(value: &Value) -> Self {
        from_glib(gobject_sys::g_value_get_enum(value.to_glib_none().0))
    }
}

impl SetValue for CollectionSortOrder {
    unsafe fn set_value(value: &mut Value, this: &Self) {
        gobject_sys::g_value_set_enum(value.to_glib_none_mut().0, this.to_glib())
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[derive(Clone, Copy)]
pub enum ComponentLayer {
    Invalid,
    Background,
    Canvas,
    Widget,
    Mdi,
    Popup,
    Overlay,
    Window,
    LastDefined,
    #[doc(hidden)]
    __Unknown(i32),
}

impl fmt::Display for ComponentLayer {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "ComponentLayer::{}", match *self {
            ComponentLayer::Invalid => "Invalid",
            ComponentLayer::Background => "Background",
            ComponentLayer::Canvas => "Canvas",
            ComponentLayer::Widget => "Widget",
            ComponentLayer::Mdi => "Mdi",
            ComponentLayer::Popup => "Popup",
            ComponentLayer::Overlay => "Overlay",
            ComponentLayer::Window => "Window",
            ComponentLayer::LastDefined => "LastDefined",
            _ => "Unknown",
        })
    }
}

#[doc(hidden)]
impl ToGlib for ComponentLayer {
    type GlibType = atspi_sys::AtspiComponentLayer;

    fn to_glib(&self) -> atspi_sys::AtspiComponentLayer {
        match *self {
            ComponentLayer::Invalid => atspi_sys::ATSPI_LAYER_INVALID,
            ComponentLayer::Background => atspi_sys::ATSPI_LAYER_BACKGROUND,
            ComponentLayer::Canvas => atspi_sys::ATSPI_LAYER_CANVAS,
            ComponentLayer::Widget => atspi_sys::ATSPI_LAYER_WIDGET,
            ComponentLayer::Mdi => atspi_sys::ATSPI_LAYER_MDI,
            ComponentLayer::Popup => atspi_sys::ATSPI_LAYER_POPUP,
            ComponentLayer::Overlay => atspi_sys::ATSPI_LAYER_OVERLAY,
            ComponentLayer::Window => atspi_sys::ATSPI_LAYER_WINDOW,
            ComponentLayer::LastDefined => atspi_sys::ATSPI_LAYER_LAST_DEFINED,
            ComponentLayer::__Unknown(value) => value
        }
    }
}

#[doc(hidden)]
impl FromGlib<atspi_sys::AtspiComponentLayer> for ComponentLayer {
    fn from_glib(value: atspi_sys::AtspiComponentLayer) -> Self {
        skip_assert_initialized!();
        match value {
            0 => ComponentLayer::Invalid,
            1 => ComponentLayer::Background,
            2 => ComponentLayer::Canvas,
            3 => ComponentLayer::Widget,
            4 => ComponentLayer::Mdi,
            5 => ComponentLayer::Popup,
            6 => ComponentLayer::Overlay,
            7 => ComponentLayer::Window,
            8 => ComponentLayer::LastDefined,
            value => ComponentLayer::__Unknown(value),
        }
    }
}

impl StaticType for ComponentLayer {
    fn static_type() -> Type {
        unsafe { from_glib(atspi_sys::atspi_component_layer_get_type()) }
    }
}

impl<'a> FromValueOptional<'a> for ComponentLayer {
    unsafe fn from_value_optional(value: &Value) -> Option<Self> {
        Some(FromValue::from_value(value))
    }
}

impl<'a> FromValue<'a> for ComponentLayer {
    unsafe fn from_value(value: &Value) -> Self {
        from_glib(gobject_sys::g_value_get_enum(value.to_glib_none().0))
    }
}

impl SetValue for ComponentLayer {
    unsafe fn set_value(value: &mut Value, this: &Self) {
        gobject_sys::g_value_set_enum(value.to_glib_none_mut().0, this.to_glib())
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[derive(Clone, Copy)]
pub enum Role {
    Invalid,
    AcceleratorLabel,
    Alert,
    Animation,
    Arrow,
    Calendar,
    Canvas,
    CheckBox,
    CheckMenuItem,
    ColorChooser,
    ColumnHeader,
    ComboBox,
    DateEditor,
    DesktopIcon,
    DesktopFrame,
    Dial,
    Dialog,
    DirectoryPane,
    DrawingArea,
    FileChooser,
    Filler,
    FocusTraversable,
    FontChooser,
    Frame,
    GlassPane,
    HtmlContainer,
    Icon,
    Image,
    InternalFrame,
    Label,
    LayeredPane,
    List,
    ListItem,
    Menu,
    MenuBar,
    MenuItem,
    OptionPane,
    PageTab,
    PageTabList,
    Panel,
    PasswordText,
    PopupMenu,
    ProgressBar,
    PushButton,
    RadioButton,
    RadioMenuItem,
    RootPane,
    RowHeader,
    ScrollBar,
    ScrollPane,
    Separator,
    Slider,
    SpinButton,
    SplitPane,
    StatusBar,
    Table,
    TableCell,
    TableColumnHeader,
    TableRowHeader,
    TearoffMenuItem,
    Terminal,
    Text,
    ToggleButton,
    ToolBar,
    ToolTip,
    Tree,
    TreeTable,
    Unknown,
    Viewport,
    Window,
    Extended,
    Header,
    Footer,
    Paragraph,
    Ruler,
    Application,
    Autocomplete,
    Editbar,
    Embedded,
    Entry,
    Chart,
    Caption,
    DocumentFrame,
    Heading,
    Page,
    Section,
    RedundantObject,
    Form,
    Link,
    InputMethodWindow,
    TableRow,
    TreeItem,
    DocumentSpreadsheet,
    DocumentPresentation,
    DocumentText,
    DocumentWeb,
    DocumentEmail,
    Comment,
    ListBox,
    Grouping,
    ImageMap,
    Notification,
    InfoBar,
    LevelBar,
    TitleBar,
    BlockQuote,
    Audio,
    Video,
    Definition,
    Article,
    Landmark,
    Log,
    Marquee,
    Math,
    Rating,
    Timer,
    Static,
    MathFraction,
    MathRoot,
    Subscript,
    Superscript,
    DescriptionList,
    DescriptionTerm,
    DescriptionValue,
    Footnote,
    LastDefined,
    #[doc(hidden)]
    __Unknown(i32),
}

impl fmt::Display for Role {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "Role::{}", match *self {
            Role::Invalid => "Invalid",
            Role::AcceleratorLabel => "AcceleratorLabel",
            Role::Alert => "Alert",
            Role::Animation => "Animation",
            Role::Arrow => "Arrow",
            Role::Calendar => "Calendar",
            Role::Canvas => "Canvas",
            Role::CheckBox => "CheckBox",
            Role::CheckMenuItem => "CheckMenuItem",
            Role::ColorChooser => "ColorChooser",
            Role::ColumnHeader => "ColumnHeader",
            Role::ComboBox => "ComboBox",
            Role::DateEditor => "DateEditor",
            Role::DesktopIcon => "DesktopIcon",
            Role::DesktopFrame => "DesktopFrame",
            Role::Dial => "Dial",
            Role::Dialog => "Dialog",
            Role::DirectoryPane => "DirectoryPane",
            Role::DrawingArea => "DrawingArea",
            Role::FileChooser => "FileChooser",
            Role::Filler => "Filler",
            Role::FocusTraversable => "FocusTraversable",
            Role::FontChooser => "FontChooser",
            Role::Frame => "Frame",
            Role::GlassPane => "GlassPane",
            Role::HtmlContainer => "HtmlContainer",
            Role::Icon => "Icon",
            Role::Image => "Image",
            Role::InternalFrame => "InternalFrame",
            Role::Label => "Label",
            Role::LayeredPane => "LayeredPane",
            Role::List => "List",
            Role::ListItem => "ListItem",
            Role::Menu => "Menu",
            Role::MenuBar => "MenuBar",
            Role::MenuItem => "MenuItem",
            Role::OptionPane => "OptionPane",
            Role::PageTab => "PageTab",
            Role::PageTabList => "PageTabList",
            Role::Panel => "Panel",
            Role::PasswordText => "PasswordText",
            Role::PopupMenu => "PopupMenu",
            Role::ProgressBar => "ProgressBar",
            Role::PushButton => "PushButton",
            Role::RadioButton => "RadioButton",
            Role::RadioMenuItem => "RadioMenuItem",
            Role::RootPane => "RootPane",
            Role::RowHeader => "RowHeader",
            Role::ScrollBar => "ScrollBar",
            Role::ScrollPane => "ScrollPane",
            Role::Separator => "Separator",
            Role::Slider => "Slider",
            Role::SpinButton => "SpinButton",
            Role::SplitPane => "SplitPane",
            Role::StatusBar => "StatusBar",
            Role::Table => "Table",
            Role::TableCell => "TableCell",
            Role::TableColumnHeader => "TableColumnHeader",
            Role::TableRowHeader => "TableRowHeader",
            Role::TearoffMenuItem => "TearoffMenuItem",
            Role::Terminal => "Terminal",
            Role::Text => "Text",
            Role::ToggleButton => "ToggleButton",
            Role::ToolBar => "ToolBar",
            Role::ToolTip => "ToolTip",
            Role::Tree => "Tree",
            Role::TreeTable => "TreeTable",
            Role::Unknown => "Unknown",
            Role::Viewport => "Viewport",
            Role::Window => "Window",
            Role::Extended => "Extended",
            Role::Header => "Header",
            Role::Footer => "Footer",
            Role::Paragraph => "Paragraph",
            Role::Ruler => "Ruler",
            Role::Application => "Application",
            Role::Autocomplete => "Autocomplete",
            Role::Editbar => "Editbar",
            Role::Embedded => "Embedded",
            Role::Entry => "Entry",
            Role::Chart => "Chart",
            Role::Caption => "Caption",
            Role::DocumentFrame => "DocumentFrame",
            Role::Heading => "Heading",
            Role::Page => "Page",
            Role::Section => "Section",
            Role::RedundantObject => "RedundantObject",
            Role::Form => "Form",
            Role::Link => "Link",
            Role::InputMethodWindow => "InputMethodWindow",
            Role::TableRow => "TableRow",
            Role::TreeItem => "TreeItem",
            Role::DocumentSpreadsheet => "DocumentSpreadsheet",
            Role::DocumentPresentation => "DocumentPresentation",
            Role::DocumentText => "DocumentText",
            Role::DocumentWeb => "DocumentWeb",
            Role::DocumentEmail => "DocumentEmail",
            Role::Comment => "Comment",
            Role::ListBox => "ListBox",
            Role::Grouping => "Grouping",
            Role::ImageMap => "ImageMap",
            Role::Notification => "Notification",
            Role::InfoBar => "InfoBar",
            Role::LevelBar => "LevelBar",
            Role::TitleBar => "TitleBar",
            Role::BlockQuote => "BlockQuote",
            Role::Audio => "Audio",
            Role::Video => "Video",
            Role::Definition => "Definition",
            Role::Article => "Article",
            Role::Landmark => "Landmark",
            Role::Log => "Log",
            Role::Marquee => "Marquee",
            Role::Math => "Math",
            Role::Rating => "Rating",
            Role::Timer => "Timer",
            Role::Static => "Static",
            Role::MathFraction => "MathFraction",
            Role::MathRoot => "MathRoot",
            Role::Subscript => "Subscript",
            Role::Superscript => "Superscript",
            Role::DescriptionList => "DescriptionList",
            Role::DescriptionTerm => "DescriptionTerm",
            Role::DescriptionValue => "DescriptionValue",
            Role::Footnote => "Footnote",
            Role::LastDefined => "LastDefined",
            _ => "Unknown",
        })
    }
}

#[doc(hidden)]
impl ToGlib for Role {
    type GlibType = atspi_sys::AtspiRole;

    fn to_glib(&self) -> atspi_sys::AtspiRole {
        match *self {
            Role::Invalid => atspi_sys::ATSPI_ROLE_INVALID,
            Role::AcceleratorLabel => atspi_sys::ATSPI_ROLE_ACCELERATOR_LABEL,
            Role::Alert => atspi_sys::ATSPI_ROLE_ALERT,
            Role::Animation => atspi_sys::ATSPI_ROLE_ANIMATION,
            Role::Arrow => atspi_sys::ATSPI_ROLE_ARROW,
            Role::Calendar => atspi_sys::ATSPI_ROLE_CALENDAR,
            Role::Canvas => atspi_sys::ATSPI_ROLE_CANVAS,
            Role::CheckBox => atspi_sys::ATSPI_ROLE_CHECK_BOX,
            Role::CheckMenuItem => atspi_sys::ATSPI_ROLE_CHECK_MENU_ITEM,
            Role::ColorChooser => atspi_sys::ATSPI_ROLE_COLOR_CHOOSER,
            Role::ColumnHeader => atspi_sys::ATSPI_ROLE_COLUMN_HEADER,
            Role::ComboBox => atspi_sys::ATSPI_ROLE_COMBO_BOX,
            Role::DateEditor => atspi_sys::ATSPI_ROLE_DATE_EDITOR,
            Role::DesktopIcon => atspi_sys::ATSPI_ROLE_DESKTOP_ICON,
            Role::DesktopFrame => atspi_sys::ATSPI_ROLE_DESKTOP_FRAME,
            Role::Dial => atspi_sys::ATSPI_ROLE_DIAL,
            Role::Dialog => atspi_sys::ATSPI_ROLE_DIALOG,
            Role::DirectoryPane => atspi_sys::ATSPI_ROLE_DIRECTORY_PANE,
            Role::DrawingArea => atspi_sys::ATSPI_ROLE_DRAWING_AREA,
            Role::FileChooser => atspi_sys::ATSPI_ROLE_FILE_CHOOSER,
            Role::Filler => atspi_sys::ATSPI_ROLE_FILLER,
            Role::FocusTraversable => atspi_sys::ATSPI_ROLE_FOCUS_TRAVERSABLE,
            Role::FontChooser => atspi_sys::ATSPI_ROLE_FONT_CHOOSER,
            Role::Frame => atspi_sys::ATSPI_ROLE_FRAME,
            Role::GlassPane => atspi_sys::ATSPI_ROLE_GLASS_PANE,
            Role::HtmlContainer => atspi_sys::ATSPI_ROLE_HTML_CONTAINER,
            Role::Icon => atspi_sys::ATSPI_ROLE_ICON,
            Role::Image => atspi_sys::ATSPI_ROLE_IMAGE,
            Role::InternalFrame => atspi_sys::ATSPI_ROLE_INTERNAL_FRAME,
            Role::Label => atspi_sys::ATSPI_ROLE_LABEL,
            Role::LayeredPane => atspi_sys::ATSPI_ROLE_LAYERED_PANE,
            Role::List => atspi_sys::ATSPI_ROLE_LIST,
            Role::ListItem => atspi_sys::ATSPI_ROLE_LIST_ITEM,
            Role::Menu => atspi_sys::ATSPI_ROLE_MENU,
            Role::MenuBar => atspi_sys::ATSPI_ROLE_MENU_BAR,
            Role::MenuItem => atspi_sys::ATSPI_ROLE_MENU_ITEM,
            Role::OptionPane => atspi_sys::ATSPI_ROLE_OPTION_PANE,
            Role::PageTab => atspi_sys::ATSPI_ROLE_PAGE_TAB,
            Role::PageTabList => atspi_sys::ATSPI_ROLE_PAGE_TAB_LIST,
            Role::Panel => atspi_sys::ATSPI_ROLE_PANEL,
            Role::PasswordText => atspi_sys::ATSPI_ROLE_PASSWORD_TEXT,
            Role::PopupMenu => atspi_sys::ATSPI_ROLE_POPUP_MENU,
            Role::ProgressBar => atspi_sys::ATSPI_ROLE_PROGRESS_BAR,
            Role::PushButton => atspi_sys::ATSPI_ROLE_PUSH_BUTTON,
            Role::RadioButton => atspi_sys::ATSPI_ROLE_RADIO_BUTTON,
            Role::RadioMenuItem => atspi_sys::ATSPI_ROLE_RADIO_MENU_ITEM,
            Role::RootPane => atspi_sys::ATSPI_ROLE_ROOT_PANE,
            Role::RowHeader => atspi_sys::ATSPI_ROLE_ROW_HEADER,
            Role::ScrollBar => atspi_sys::ATSPI_ROLE_SCROLL_BAR,
            Role::ScrollPane => atspi_sys::ATSPI_ROLE_SCROLL_PANE,
            Role::Separator => atspi_sys::ATSPI_ROLE_SEPARATOR,
            Role::Slider => atspi_sys::ATSPI_ROLE_SLIDER,
            Role::SpinButton => atspi_sys::ATSPI_ROLE_SPIN_BUTTON,
            Role::SplitPane => atspi_sys::ATSPI_ROLE_SPLIT_PANE,
            Role::StatusBar => atspi_sys::ATSPI_ROLE_STATUS_BAR,
            Role::Table => atspi_sys::ATSPI_ROLE_TABLE,
            Role::TableCell => atspi_sys::ATSPI_ROLE_TABLE_CELL,
            Role::TableColumnHeader => atspi_sys::ATSPI_ROLE_TABLE_COLUMN_HEADER,
            Role::TableRowHeader => atspi_sys::ATSPI_ROLE_TABLE_ROW_HEADER,
            Role::TearoffMenuItem => atspi_sys::ATSPI_ROLE_TEAROFF_MENU_ITEM,
            Role::Terminal => atspi_sys::ATSPI_ROLE_TERMINAL,
            Role::Text => atspi_sys::ATSPI_ROLE_TEXT,
            Role::ToggleButton => atspi_sys::ATSPI_ROLE_TOGGLE_BUTTON,
            Role::ToolBar => atspi_sys::ATSPI_ROLE_TOOL_BAR,
            Role::ToolTip => atspi_sys::ATSPI_ROLE_TOOL_TIP,
            Role::Tree => atspi_sys::ATSPI_ROLE_TREE,
            Role::TreeTable => atspi_sys::ATSPI_ROLE_TREE_TABLE,
            Role::Unknown => atspi_sys::ATSPI_ROLE_UNKNOWN,
            Role::Viewport => atspi_sys::ATSPI_ROLE_VIEWPORT,
            Role::Window => atspi_sys::ATSPI_ROLE_WINDOW,
            Role::Extended => atspi_sys::ATSPI_ROLE_EXTENDED,
            Role::Header => atspi_sys::ATSPI_ROLE_HEADER,
            Role::Footer => atspi_sys::ATSPI_ROLE_FOOTER,
            Role::Paragraph => atspi_sys::ATSPI_ROLE_PARAGRAPH,
            Role::Ruler => atspi_sys::ATSPI_ROLE_RULER,
            Role::Application => atspi_sys::ATSPI_ROLE_APPLICATION,
            Role::Autocomplete => atspi_sys::ATSPI_ROLE_AUTOCOMPLETE,
            Role::Editbar => atspi_sys::ATSPI_ROLE_EDITBAR,
            Role::Embedded => atspi_sys::ATSPI_ROLE_EMBEDDED,
            Role::Entry => atspi_sys::ATSPI_ROLE_ENTRY,
            Role::Chart => atspi_sys::ATSPI_ROLE_CHART,
            Role::Caption => atspi_sys::ATSPI_ROLE_CAPTION,
            Role::DocumentFrame => atspi_sys::ATSPI_ROLE_DOCUMENT_FRAME,
            Role::Heading => atspi_sys::ATSPI_ROLE_HEADING,
            Role::Page => atspi_sys::ATSPI_ROLE_PAGE,
            Role::Section => atspi_sys::ATSPI_ROLE_SECTION,
            Role::RedundantObject => atspi_sys::ATSPI_ROLE_REDUNDANT_OBJECT,
            Role::Form => atspi_sys::ATSPI_ROLE_FORM,
            Role::Link => atspi_sys::ATSPI_ROLE_LINK,
            Role::InputMethodWindow => atspi_sys::ATSPI_ROLE_INPUT_METHOD_WINDOW,
            Role::TableRow => atspi_sys::ATSPI_ROLE_TABLE_ROW,
            Role::TreeItem => atspi_sys::ATSPI_ROLE_TREE_ITEM,
            Role::DocumentSpreadsheet => atspi_sys::ATSPI_ROLE_DOCUMENT_SPREADSHEET,
            Role::DocumentPresentation => atspi_sys::ATSPI_ROLE_DOCUMENT_PRESENTATION,
            Role::DocumentText => atspi_sys::ATSPI_ROLE_DOCUMENT_TEXT,
            Role::DocumentWeb => atspi_sys::ATSPI_ROLE_DOCUMENT_WEB,
            Role::DocumentEmail => atspi_sys::ATSPI_ROLE_DOCUMENT_EMAIL,
            Role::Comment => atspi_sys::ATSPI_ROLE_COMMENT,
            Role::ListBox => atspi_sys::ATSPI_ROLE_LIST_BOX,
            Role::Grouping => atspi_sys::ATSPI_ROLE_GROUPING,
            Role::ImageMap => atspi_sys::ATSPI_ROLE_IMAGE_MAP,
            Role::Notification => atspi_sys::ATSPI_ROLE_NOTIFICATION,
            Role::InfoBar => atspi_sys::ATSPI_ROLE_INFO_BAR,
            Role::LevelBar => atspi_sys::ATSPI_ROLE_LEVEL_BAR,
            Role::TitleBar => atspi_sys::ATSPI_ROLE_TITLE_BAR,
            Role::BlockQuote => atspi_sys::ATSPI_ROLE_BLOCK_QUOTE,
            Role::Audio => atspi_sys::ATSPI_ROLE_AUDIO,
            Role::Video => atspi_sys::ATSPI_ROLE_VIDEO,
            Role::Definition => atspi_sys::ATSPI_ROLE_DEFINITION,
            Role::Article => atspi_sys::ATSPI_ROLE_ARTICLE,
            Role::Landmark => atspi_sys::ATSPI_ROLE_LANDMARK,
            Role::Log => atspi_sys::ATSPI_ROLE_LOG,
            Role::Marquee => atspi_sys::ATSPI_ROLE_MARQUEE,
            Role::Math => atspi_sys::ATSPI_ROLE_MATH,
            Role::Rating => atspi_sys::ATSPI_ROLE_RATING,
            Role::Timer => atspi_sys::ATSPI_ROLE_TIMER,
            Role::Static => atspi_sys::ATSPI_ROLE_STATIC,
            Role::MathFraction => atspi_sys::ATSPI_ROLE_MATH_FRACTION,
            Role::MathRoot => atspi_sys::ATSPI_ROLE_MATH_ROOT,
            Role::Subscript => atspi_sys::ATSPI_ROLE_SUBSCRIPT,
            Role::Superscript => atspi_sys::ATSPI_ROLE_SUPERSCRIPT,
            Role::DescriptionList => atspi_sys::ATSPI_ROLE_DESCRIPTION_LIST,
            Role::DescriptionTerm => atspi_sys::ATSPI_ROLE_DESCRIPTION_TERM,
            Role::DescriptionValue => atspi_sys::ATSPI_ROLE_DESCRIPTION_VALUE,
            Role::Footnote => atspi_sys::ATSPI_ROLE_FOOTNOTE,
            Role::LastDefined => atspi_sys::ATSPI_ROLE_LAST_DEFINED,
            Role::__Unknown(value) => value
        }
    }
}

#[doc(hidden)]
impl FromGlib<atspi_sys::AtspiRole> for Role {
    fn from_glib(value: atspi_sys::AtspiRole) -> Self {
        skip_assert_initialized!();
        match value {
            0 => Role::Invalid,
            1 => Role::AcceleratorLabel,
            2 => Role::Alert,
            3 => Role::Animation,
            4 => Role::Arrow,
            5 => Role::Calendar,
            6 => Role::Canvas,
            7 => Role::CheckBox,
            8 => Role::CheckMenuItem,
            9 => Role::ColorChooser,
            10 => Role::ColumnHeader,
            11 => Role::ComboBox,
            12 => Role::DateEditor,
            13 => Role::DesktopIcon,
            14 => Role::DesktopFrame,
            15 => Role::Dial,
            16 => Role::Dialog,
            17 => Role::DirectoryPane,
            18 => Role::DrawingArea,
            19 => Role::FileChooser,
            20 => Role::Filler,
            21 => Role::FocusTraversable,
            22 => Role::FontChooser,
            23 => Role::Frame,
            24 => Role::GlassPane,
            25 => Role::HtmlContainer,
            26 => Role::Icon,
            27 => Role::Image,
            28 => Role::InternalFrame,
            29 => Role::Label,
            30 => Role::LayeredPane,
            31 => Role::List,
            32 => Role::ListItem,
            33 => Role::Menu,
            34 => Role::MenuBar,
            35 => Role::MenuItem,
            36 => Role::OptionPane,
            37 => Role::PageTab,
            38 => Role::PageTabList,
            39 => Role::Panel,
            40 => Role::PasswordText,
            41 => Role::PopupMenu,
            42 => Role::ProgressBar,
            43 => Role::PushButton,
            44 => Role::RadioButton,
            45 => Role::RadioMenuItem,
            46 => Role::RootPane,
            47 => Role::RowHeader,
            48 => Role::ScrollBar,
            49 => Role::ScrollPane,
            50 => Role::Separator,
            51 => Role::Slider,
            52 => Role::SpinButton,
            53 => Role::SplitPane,
            54 => Role::StatusBar,
            55 => Role::Table,
            56 => Role::TableCell,
            57 => Role::TableColumnHeader,
            58 => Role::TableRowHeader,
            59 => Role::TearoffMenuItem,
            60 => Role::Terminal,
            61 => Role::Text,
            62 => Role::ToggleButton,
            63 => Role::ToolBar,
            64 => Role::ToolTip,
            65 => Role::Tree,
            66 => Role::TreeTable,
            67 => Role::Unknown,
            68 => Role::Viewport,
            69 => Role::Window,
            70 => Role::Extended,
            71 => Role::Header,
            72 => Role::Footer,
            73 => Role::Paragraph,
            74 => Role::Ruler,
            75 => Role::Application,
            76 => Role::Autocomplete,
            77 => Role::Editbar,
            78 => Role::Embedded,
            79 => Role::Entry,
            80 => Role::Chart,
            81 => Role::Caption,
            82 => Role::DocumentFrame,
            83 => Role::Heading,
            84 => Role::Page,
            85 => Role::Section,
            86 => Role::RedundantObject,
            87 => Role::Form,
            88 => Role::Link,
            89 => Role::InputMethodWindow,
            90 => Role::TableRow,
            91 => Role::TreeItem,
            92 => Role::DocumentSpreadsheet,
            93 => Role::DocumentPresentation,
            94 => Role::DocumentText,
            95 => Role::DocumentWeb,
            96 => Role::DocumentEmail,
            97 => Role::Comment,
            98 => Role::ListBox,
            99 => Role::Grouping,
            100 => Role::ImageMap,
            101 => Role::Notification,
            102 => Role::InfoBar,
            103 => Role::LevelBar,
            104 => Role::TitleBar,
            105 => Role::BlockQuote,
            106 => Role::Audio,
            107 => Role::Video,
            108 => Role::Definition,
            109 => Role::Article,
            110 => Role::Landmark,
            111 => Role::Log,
            112 => Role::Marquee,
            113 => Role::Math,
            114 => Role::Rating,
            115 => Role::Timer,
            116 => Role::Static,
            117 => Role::MathFraction,
            118 => Role::MathRoot,
            119 => Role::Subscript,
            120 => Role::Superscript,
            121 => Role::DescriptionList,
            122 => Role::DescriptionTerm,
            123 => Role::DescriptionValue,
            124 => Role::Footnote,
            125 => Role::LastDefined,
            value => Role::__Unknown(value),
        }
    }
}

impl StaticType for Role {
    fn static_type() -> Type {
        unsafe { from_glib(atspi_sys::atspi_role_get_type()) }
    }
}

impl<'a> FromValueOptional<'a> for Role {
    unsafe fn from_value_optional(value: &Value) -> Option<Self> {
        Some(FromValue::from_value(value))
    }
}

impl<'a> FromValue<'a> for Role {
    unsafe fn from_value(value: &Value) -> Self {
        from_glib(gobject_sys::g_value_get_enum(value.to_glib_none().0))
    }
}

impl SetValue for Role {
    unsafe fn set_value(value: &mut Value, this: &Self) {
        gobject_sys::g_value_set_enum(value.to_glib_none_mut().0, this.to_glib())
    }
}

#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[derive(Clone, Copy)]
pub enum TextGranularity {
    Char,
    Word,
    Sentence,
    Line,
    Paragraph,
    #[doc(hidden)]
    __Unknown(i32),
}

impl fmt::Display for TextGranularity {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "TextGranularity::{}", match *self {
            TextGranularity::Char => "Char",
            TextGranularity::Word => "Word",
            TextGranularity::Sentence => "Sentence",
            TextGranularity::Line => "Line",
            TextGranularity::Paragraph => "Paragraph",
            _ => "Unknown",
        })
    }
}

#[doc(hidden)]
impl ToGlib for TextGranularity {
    type GlibType = atspi_sys::AtspiTextGranularity;

    fn to_glib(&self) -> atspi_sys::AtspiTextGranularity {
        match *self {
            TextGranularity::Char => atspi_sys::ATSPI_TEXT_GRANULARITY_CHAR,
            TextGranularity::Word => atspi_sys::ATSPI_TEXT_GRANULARITY_WORD,
            TextGranularity::Sentence => atspi_sys::ATSPI_TEXT_GRANULARITY_SENTENCE,
            TextGranularity::Line => atspi_sys::ATSPI_TEXT_GRANULARITY_LINE,
            TextGranularity::Paragraph => atspi_sys::ATSPI_TEXT_GRANULARITY_PARAGRAPH,
            TextGranularity::__Unknown(value) => value
        }
    }
}

#[doc(hidden)]
impl FromGlib<atspi_sys::AtspiTextGranularity> for TextGranularity {
    fn from_glib(value: atspi_sys::AtspiTextGranularity) -> Self {
        skip_assert_initialized!();
        match value {
            0 => TextGranularity::Char,
            1 => TextGranularity::Word,
            2 => TextGranularity::Sentence,
            3 => TextGranularity::Line,
            4 => TextGranularity::Paragraph,
            value => TextGranularity::__Unknown(value),
        }
    }
}

impl StaticType for TextGranularity {
    fn static_type() -> Type {
        unsafe { from_glib(atspi_sys::atspi_text_granularity_get_type()) }
    }
}

impl<'a> FromValueOptional<'a> for TextGranularity {
    unsafe fn from_value_optional(value: &Value) -> Option<Self> {
        Some(FromValue::from_value(value))
    }
}

impl<'a> FromValue<'a> for TextGranularity {
    unsafe fn from_value(value: &Value) -> Self {
        from_glib(gobject_sys::g_value_get_enum(value.to_glib_none().0))
    }
}

impl SetValue for TextGranularity {
    unsafe fn set_value(value: &mut Value, this: &Self) {
        gobject_sys::g_value_set_enum(value.to_glib_none_mut().0, this.to_glib())
    }
}

