// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use atspi_sys;
use glib::translate::*;
use gobject_sys;

glib_wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct Event(Boxed<atspi_sys::AtspiEvent>);

    match fn {
        copy => |ptr| gobject_sys::g_boxed_copy(atspi_sys::atspi_event_get_type(), ptr as *mut _) as *mut atspi_sys::AtspiEvent,
        free => |ptr| gobject_sys::g_boxed_free(atspi_sys::atspi_event_get_type(), ptr as *mut _),
        get_type => || atspi_sys::atspi_event_get_type(),
    }
}

impl Event {
    pub fn main() {
        assert_initialized_main_thread!();
        unsafe {
            atspi_sys::atspi_event_main();
        }
    }

    pub fn quit() {
        assert_initialized_main_thread!();
        unsafe {
            atspi_sys::atspi_event_quit();
        }
    }
}
