// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use Hyperlink;
use atspi_sys;
use glib;
use glib::object::IsA;
use glib::translate::*;
use std::fmt;
use std::ptr;

glib_wrapper! {
    pub struct Hypertext(Interface<atspi_sys::AtspiHypertext>);

    match fn {
        get_type => || atspi_sys::atspi_hypertext_get_type(),
    }
}

pub const NONE_HYPERTEXT: Option<&Hypertext> = None;

pub trait HypertextExt: 'static {
    fn get_link(&self, link_index: i32) -> Result<Option<Hyperlink>, glib::Error>;

    fn get_link_index(&self, character_offset: i32) -> Result<i32, glib::Error>;

    fn get_n_links(&self) -> Result<i32, glib::Error>;
}

impl<O: IsA<Hypertext>> HypertextExt for O {
    fn get_link(&self, link_index: i32) -> Result<Option<Hyperlink>, glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = atspi_sys::atspi_hypertext_get_link(self.as_ref().to_glib_none().0, link_index, &mut error);
            if error.is_null() { Ok(from_glib_full(ret)) } else { Err(from_glib_full(error)) }
        }
    }

    fn get_link_index(&self, character_offset: i32) -> Result<i32, glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = atspi_sys::atspi_hypertext_get_link_index(self.as_ref().to_glib_none().0, character_offset, &mut error);
            if error.is_null() { Ok(ret) } else { Err(from_glib_full(error)) }
        }
    }

    fn get_n_links(&self) -> Result<i32, glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = atspi_sys::atspi_hypertext_get_n_links(self.as_ref().to_glib_none().0, &mut error);
            if error.is_null() { Ok(ret) } else { Err(from_glib_full(error)) }
        }
    }
}

impl fmt::Display for Hypertext {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "Hypertext")
    }
}
