// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use glib::translate::*;
use std::fmt;

glib::glib_wrapper! {
    pub struct Object(Object<ffi::AtspiObject, ffi::AtspiObjectClass>);

    match fn {
        get_type => || ffi::atspi_object_get_type(),
    }
}

impl Object {}

pub const NONE_OBJECT: Option<&Object> = None;

impl fmt::Display for Object {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("Object")
    }
}
