// This file was generated by gir (https://github.com/gtk-rs/gir @ 7cca816)
// from gir-files (https://github.com/gtk-rs/gir-files @ 02dfee2)
// DO NOT EDIT

use atspi_sys;
use glib::translate::*;
use std::fmt;

glib_wrapper! {
    pub struct Object(Object<atspi_sys::AtspiObject, atspi_sys::AtspiObjectClass, ObjectClass>);

    match fn {
        get_type => || atspi_sys::atspi_object_get_type(),
    }
}

impl Object {}

pub const NONE_OBJECT: Option<&Object> = None;

impl fmt::Display for Object {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "Object")
    }
}
