// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use crate::Accessible;
use crate::RelationType;
use glib::object::IsA;
use glib::translate::*;
use std::fmt;

glib::wrapper! {
    pub struct Relation(Object<ffi::AtspiRelation, ffi::AtspiRelationClass>);

    match fn {
        get_type => || ffi::atspi_relation_get_type(),
    }
}

pub const NONE_RELATION: Option<&Relation> = None;

pub trait RelationExt: 'static {
    #[doc(alias = "atspi_relation_get_n_targets")]
    fn get_n_targets(&self) -> i32;

    #[doc(alias = "atspi_relation_get_relation_type")]
    fn get_relation_type(&self) -> RelationType;

    #[doc(alias = "atspi_relation_get_target")]
    fn get_target(&self, i: i32) -> Option<Accessible>;
}

impl<O: IsA<Relation>> RelationExt for O {
    fn get_n_targets(&self) -> i32 {
        unsafe {
            ffi::atspi_relation_get_n_targets(self.as_ref().to_glib_none().0)
        }
    }

    fn get_relation_type(&self) -> RelationType {
        unsafe {
            from_glib(ffi::atspi_relation_get_relation_type(self.as_ref().to_glib_none().0))
        }
    }

    fn get_target(&self, i: i32) -> Option<Accessible> {
        unsafe {
            from_glib_full(ffi::atspi_relation_get_target(self.as_ref().to_glib_none().0, i))
        }
    }
}

impl fmt::Display for Relation {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("Relation")
    }
}
