[options]
work_mode = "sys"
girs_dir = "../gir-files-20.04/"
library = "Atspi"
version = "2.0"
target_path = "."
min_cfg_version = "2.28"
single_version_file = "."

external_libraries = [
   "GLib",
   "Gio",
   "GObject",
]

ignore = []
