// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// methods were written manually

use atspi_sys;
use gobject_sys;

glib_wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct Rect(Boxed<atspi_sys::AtspiRect>);

    match fn {
        copy => |ptr| gobject_sys::g_boxed_copy(atspi_sys::atspi_rect_get_type(), ptr as *mut _) as *mut atspi_sys::AtspiRect,
        free => |ptr| gobject_sys::g_boxed_free(atspi_sys::atspi_rect_get_type(), ptr as *mut _),
        get_type => || atspi_sys::atspi_rect_get_type(),
    }
}

impl Rect {
    pub fn get_x(&self) -> i32 {
        self.0.x as i32
    }
    pub fn get_y(&self) -> i32 {
        self.0.y as i32
    }
    pub fn get_width(&self) -> i32 {
        self.0.width as i32
    }
    pub fn get_height(&self) -> i32 {
        self.0.height as i32
    }
}
